### ISSUE TITLE
[ENHANCEMENT] move code to test-support directory

### ISSUE THREAD

**Issue by williamsbdev** [san650/ember-cli-page-object#1]
This looks like a great project! I'm excited to try this out.

Something that I noticed was that all the code is in the `addon` directory. It is not really needed outside of  testing. Because of that, I might recommend moving the code into the test-support directory so as not to bloat the production build of your hosting app.

I was unaware of this feature until @bcardarella pointed it out in an [addon](https://github.com/toranb/ember-cli-test-helpers/issues/6) that I am heavily involved with. I also wrote a really quick [blog post](http://williamsbdev.com/posts/Ember-CLI-test-support/) (mainly for myself) about the feature.

Again, looking forward to trying out this addon. Thanks!

**Comment by san650** [comment]
Thanks for you suggestions, I'll move the code to test-support. Can you point me to some documentation about that folder? I couldn't find good documentation on how to build an ember-cli addon focused on creating testing helpers.

I'm really glad you liked the project and I really appreciate your feedback!

**Comment by williamsbdev** [comment]
There isn't much documentation yet. Projects are the best documentation we have right now. You can checkout the addon I referenced above, the blog post I wrote, or this [example](https://github.com/dockyard/ember-validations/tree/master/test-support/helpers). That is where I stole my inspiration from. If you'd like to pair up sometime, let me know.
