### ISSUE TITLE
Add tests for blueprints

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#100]
It would be really cool to add tests for blueprints

https://github.com/ember-cli/ember-cli-blueprint-test-helpers

**Comment by jeradg** [comment]
@san650: Working on this in https://github.com/san650/ember-cli-page-object/pull/145.

I presume we should add the blueprint tests to Travis when they're up and running?

**Comment by san650** [comment]
@jeradg Yes, we should.

**Comment by san650** [comment]
Fixed by #145
