### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by MondeSameWave** [san650/ember-cli-page-object#118]
How do I trigger a change in a checkbox

<input id="ember1663" type="checkbox" class="checkbox ember-view ember-checkbox">

**Comment by san650** [comment]
You should use the [`.clickable`](http://ember-cli-page-object.js.org/api/actions/#clickable) or [`.clickOnText`](http://ember-cli-page-object.js.org/api/actions/#clickontext) attributes.

Let's say you have the following HTML fragment

```html
<fieldset>
  <label>
    <input type="checkbox"> Option A
  </label>
  <label>
    <input type="checkbox"> Option B
  </label>
</fieldset>
```

You can build a page object like

```js
var page = PageObject.create({
  options: {
    scope: 'fieldset'
  }
});

page.options().clickOn('Option B');
```

Here I'm using one of the [auto generated](http://ember-cli-page-object.js.org/api/components/#default-attributes) attributes.

Please, let me know how it goes!

**Comment by MondeSameWave** [comment]
Thanks
