### ISSUE TITLE
Page Objects don't install correct in addon projects

### ISSUE THREAD

**Issue by foxnewsnetwork** [san650/ember-cli-page-object#124]
In reference to this other issue: https://github.com/san650/ember-cli-page-object/issues/61#issuecomment-181629831

The basic gist of it is that the loader can't find Page Object inside an addon project because it expects the PageObject to live inside `<%= project_name%>/tests/page-object` when it actually lives inside `dummy/tests/page-object`

**Comment by jeradg** [comment]
@foxnewsnetwork: This should work now in ember-cli-page-object v1.2.0. Can you install the new version and confirm?

**Comment by jeradg** [comment]
@foxnewsnetwork: Closing this issue. Please reopen if you're still having blueprint troubles.

**Comment by foxnewsnetwork** [comment]
yeah, just tried it out on a new install, things are working :+1:

**Comment by jeradg** [comment]
@foxnewsnetwork: Great! Thanks for confirming.
