### ISSUE TITLE
What to do about customHelper removal?

### ISSUE THREAD

**Issue by kmiyashiro** [san650/ember-cli-page-object#127]
I noticed 1.0.0 removes `customHelper`, what is the upgrade path for existing custom helpers?

**Comment by juanazam** [comment]
@kmiyashiro, there are multiple ways to move away from `customHelper`, it depends for what you are using it, can you show a particular case you might be worried about?

WIth 1.0.0, we have changed the way we generate PageObjects completely. The idea is that user would move away from `customHelper` to building their own [Ceibo](https://github.com/san650/ceibo) descriptors (all existing properties of the project have been moved to that format). This will give users all the necessary power to build whatever they need.

**Comment by kmiyashiro** [comment]
I use `customHelper` to add a keyEvent and triggerEvent helpers

```js
/* global keyEvent */

import PageObject from '../../page-object';

function _keyEvent(selector) {
  return function(eventName, keyCode) {
    return keyEvent(selector, eventName || 'keypress', keyCode || 13);
  };
}

export default PageObject.customHelper(_keyEvent);
```

**Comment by juanazam** [comment]
@kmiyashiro we have the same code on one project I found this very funny :smile: 

You can build a propery in the `v1` one, for example: https://github.com/san650/ember-cli-page-object/blob/master/test-support/page-object/properties/fillable.js.

```js
export function _keyEvent(selector, options = {}) {
  return {
    isDescriptor: true,

    value(eventName, keyCode) {
      let processedSelector = buildSelector(selector, options);
      /* global keyEvent */
      return keyEvent(selector, eventName || 'keypress', keyCode || 13);
    }
  }
}
```

On this exampe I'm using the `buildSelector` helper build a selector based on where the `Ceibo` descriptor is within the PageObject definition and also allows the usage of options suchs `scope`, `resetScope` and `at`.

You can see how that works over here: com/san650/ember-cli-page-object/blob/master/test-support/page-object/helpers.js#L88

Anyway, we are aiming to write about this on the site so users know how can they do this.

Hope this is helpful.

**Comment by kmiyashiro** [comment]
I see. And you call these things `properties` now?

**Comment by juanazam** [comment]
On the page object project we have properties that are `Ceibo` descriptors. Example: `clickable` property is build using `Ceibo` we say it is a `Ceibo` descriptor.

**Comment by juanazam** [comment]
@kmiyashiro we have finally released v1, I added [this](http://ember-cli-page-object.js.org/docs/v1.0.x/components) example to the official documentation. You can join the `ember-cli-page-object` channel in slack if you have more doubts. I'm closing this issue.

**Comment by san650** [comment]
@kmiyashiro I add a helper to do this in another project, https://github.com/san650/tajpado/blob/9e34624bd60251f2163614aaa41555027ff975a4/tests/pages/activity.js#L3-L11

Also, as Juan said, this link has an example http://ember-cli-page-object.js.org/docs/v1.0.x/components#customhelper

Maybe we could add the a keyEvent property action to ember-cli-page-object, What do you think @kmiyashiro

**Comment by kmiyashiro** [comment]
@san650 I think adding a keyEvent action would be a good idea, key events are almost as common as clicks when testing apps.

**Comment by juanazam** [comment]
@kmiyashiro I have thought about adding event actions on every component might be a good idea. `keyEvent`, `blur` and other.

@san650 what do you think?
