### ISSUE TITLE
PO.selectable

### ISSUE THREAD

**Issue by knownasilya** [san650/ember-cli-page-object#13]
For setting a value on a select field..

**Comment by juanazam** [comment]
There are plans for providing support for a bunch of form attributes.

**Comment by san650** [comment]
Hi @knownasilya, thanks for your suggestion. It would be very useful to have an attribute helper for that.

I imagine a helper that selects an option by option's text. 

```html
<select class="countries">
  <option>Afghanistan</option>
  <option>Albania</option>
  ...
</select>
```

```js
selectable: function(selector) {
  return function(value) {
    return fillIn(selector, value);
  }
}

var page = PageObject.build({
  country: selectable('.countries')
});

page
  .visit()
  .select('Uruguay');

andThen(function() {
  ...
});
```

Other alternatives would be to select an option by value or index... I'm not sure what's more useful. What do you think?

**Comment by knownasilya** [comment]
Probably by text. It would be easier to write the tests without having to inspect the html.
