### ISSUE TITLE
is there a way to set the find scope? to be able to test modal dialog elements

### ISSUE THREAD

**Issue by danielspaniel** [san650/ember-cli-page-object#132]
Am really enjoying this addon. 

And I was wondering if there is a way to test modal-dialogs which attach themselves to the body and float outside the #ember-testing-container which all the find('class-selector') are usually scoped to.

 I can do this ( with plain old ember test helper find ):

 find('model-class-selector', 'body') // where I can change the scope to 'body'

 but is there a way to do this and still use your clickable and value, fillable and all the other helper methods?  Not sure how to send this scope of 'body' for the find call into your helper methods?

 has anyone done this already?
  any hints?

**Comment by juanazam** [comment]
Hey @danielspaniel I'm happy to hear you are enjoying it.

I'm not 100% sure, but I think there is no easy way of doing this (querying within 'body' and also keep everything working with the addon's features).

Are we talking about something like:

```js
let page = PageObject.create({
  scope: '.page',

  modal: {
     scope: "#my-modal",
     resetScope: true,
     fillInName: fillable('#name')
  }
}

page.modal.fillIn('Juan') // translates into find('#my-modal #name').val('Juan') using Ember's testing find method which looks within "#ember-testing-container".
```

I'm not sure if there is a way of overriding or changing how Ember's testing `find` method works, but in case it would be possible, we could add a 'global' options or something. But I said before, I'm nor sure if this approach would work.

**Comment by danielspaniel** [comment]
yes .. that is what I was thinking too

```js
let page = PageObject.create({
  scope: 'body', // ? not sure

  modal: {
     scope: "#my-modal",
     resetScope: true,
     fillInName: fillable('#name')
  }
}
```

what we would need is for it to then do:

```js
 find('#my-modal #name', 'body').val('Juan')
```

so it would not be overriding ember-test helper .. just using it and passing in the body selector. 
 You know the internals of page object pretty well, so if you think it can be done I am willing to give it a shot too.

**Comment by juanazam** [comment]
Looking into https://github.com/emberjs/ember.js/blob/v2.3.0/packages/ember-testing/lib/helpers.js#L170 it seems we can pass body as an argument, I guess we can build this feature and it shouldn't be too hard. Passing a "rootElement" to the `findCall` we do, if the options is set.

**Comment by danielspaniel** [comment]
right .. do you want to give it a shot or help me do it?  I can get on screen hero sometime tonight or tomorrow if you like?

**Comment by danielspaniel** [comment]
or you could temporarily set the rootElement on the application .. but that is pretty bad style

**Comment by jeradg** [comment]
@danielspaniel: Alternately, you could re-write the modal to attach itself to the Ember app's `rootElement` rather than to `body`. (This might be a good idea anyway: The docs for `Ember.Application` note that "views appended to the DOM outside the root element will not receive events".)

**Comment by danielspaniel** [comment]
hmm .. that was good idea .. @jeradg .. me like .. but not sure how to do that .. 
 checking ...

**Comment by danielspaniel** [comment]
looks like there is target property on ember-modal-dialog .. ( which defaults to 'body' )  I will see if I can set it to ember rootElement and then see if the tests work ( great idea dude )

**Comment by jeradg** [comment]
The docs for ember-modal-dialog say that you can set target to an Ember View. Maybe you can set it to the application view? (Just a guess. I've never worked with that addon.)

**Comment by danielspaniel** [comment]
trying that now and using  Ember.getOwner(this).rootElement   to get that name .. so far looking promising

**Comment by jeradg** [comment]
Since this seems to mostly be a usage question rather than an issue per se, we can always continue this discussion in the ember-cli-page-object channel on the Ember Slack community. (https://embercommunity.slack.com/messages/ember-cli-page-object)

**Comment by danielspaniel** [comment]
sure thing

**Comment by san650** [comment]
I think this is a really good question to have in a FAQ in the site, I struggled with this problem in a project I have and the solution was to change the modal library I was using (tooltipster) to append to the application's root element.

Apart from that It would be nice to have an alternative to set the findElement scope for those cases when you don't have control on where the modal/tooltip or whatever appends to on the page. I'm going to think a bit about the API to achieve this but it could be something like having a rootElement property/option for all page object properties

```js
var page = PageObject.extend({
  modal: {
    rootElement: 'body'
  },

  title: text('.modal h1', { rootElement: 'body' })
}

page.modal.text // find('', 'body').text()
page.title // find('.modal h1', 'body').text()
```
