### ISSUE TITLE
[Docs] Add documentation for `selectable`

### ISSUE THREAD

**Issue by jeradg** [san650/ember-cli-page-object#141]
`selectable` is an alias for `fillable`, but that's not mentioned on the docs site.

**Comment by san650** [comment]
Can we use the `@alias` tag? http://usejsdoc.org/tags-alias.html

**Comment by jeradg** [comment]
That's what I was thinking. Don't know what Markdown that results in, but it should be a starting point.

**Comment by jeradg** [comment]
@san650: `@alias` doesn't work, because it overwrites the original name. I found a workaround though. Creating a PR.

**Comment by jeradg** [comment]
@san650: See https://github.com/san650/ember-cli-page-object/pull/146. I'd be happy to hear your feedback.
