### ISSUE TITLE
Mention Ceibo dependency

### ISSUE THREAD

**Issue by zeppelin** [san650/ember-cli-page-object#152]
Upgrading `ember-cli-page-object` may leave users wondering why their app is no longer booting (Ceibo silently became a Bower dependency.)

**Comment by san650** [comment]
@zeppelin I've created #157 to tackle this issue. Please, let me know if you think the comment I added is enough or if we need to be more specific about the bower dependency.

**Comment by jeradg** [comment]
@san650: We should probably also add this to the "Installation" page on the docs site (for `v1.0.x` and `v1.1.x`) and to the release notes.

**Comment by san650** [comment]
@jeradg that's true, I forgot about that. I'll add that tomorrow

**Comment by zeppelin** [comment]
@san650 looks great, thanks for adding this to the readme!
