### ISSUE TITLE
`Ember.merge` is deprecated, use `Ember.assign`

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#153]
This deprecation notice is being thrown when using ember beta and canary.

**Comment by pangratz** [comment]
Should be fixed by emberjs/data#4250

**Comment by vvscode** [comment]
Is it what we need? https://github.com/san650/ember-cli-page-object/pull/160

**Comment by san650** [comment]
@vvscode Yes, and again, thanks for contributing. I left a comment in the PR

**Comment by san650** [comment]
Fixed by #160
