### ISSUE TITLE
selectors and iframe

### ISSUE THREAD

**Issue by Sinled** [san650/ember-cli-page-object#154]
Hi, at first thanks for this handy plugin.

I have a small question.
Is it possible to target elements inside iframe via ember-cli-page-object api?

There is wysiwyg editor in my project, it replaces default texatreas with iframes, and i can`t figure how to address them in my page objects.

**Comment by san650** [comment]
Hi @Sinled, it isn't... __but__ you can create a page object with custom attributes that read information from the iframe's document.

You'll need to:
1. Get iframe's document
2. Look for elements and extract information
3. Trigger changes

An example:

```js
import Ember from 'ember';
import { create, visitable } from '../page-object';

var { $ } = Ember;

function iframe(selector) {
  return {
    isDescriptor: true,
    get() {
      var iframe = $(selector).get(0),
          doc = iframe.contentWindow.document;

      return $(doc.body);
    }
  };
}

function text(selector) {
  return {
    isDescriptor: true,
    get() {
      // I'm assuming here that `page.iframe` exists
      return $(selector, this.iframe).text();
    }
  };
}

function fill(selector) {
  return {
    isDescriptor: true,
    value(text) {
      // I'm assuming here that `page.iframe` exists
      return $(selector, this.iframe).text(text);
    }
  };
}

export default create({
  visit: visitable('/my-page'),

  iframe: iframe('iframe.my-wysiwyg-editor'),

  text: text('.selector-inside-iframe'),

  write: fill('.selector-inside-iframe')
});
```

This way you could use that page object as follows

```js
test('writes inside the WYSIWYG editor', function(assert) {
  page.visit().write('Hello World!');

  andThen(function() {
    assert.equal(page.text, 'Hello World!');
  });
});
```

Please, let me know if you find this useful and if it works for you. It might be a good idea to start considering a solution to target different documents (iframes).

**Comment by juanazam** [comment]
@Sinled would yo able to get this done with @san650 suggestion? can we close this?

**Comment by Sinled** [comment]
Sorry, missed response, suggestion worked for me.
