### ISSUE TITLE
[Site] Component default attribute links are broken

### ISSUE THREAD

**Issue by thomascchen** [san650/ember-cli-page-object#166]
The links to the default attributes on the component page are broken:
- isVisible
- isHidden
- clickOn
- click
- contains
- text

The path appears to be missing `/docs/*version*` before `/api/predicates/#isvisible`

**Comment by juanazam** [comment]
@thomascchen you are right, thanks! we will fix this ASAP

**Comment by juanazam** [comment]
@thomascchen this is fixed, I'm closing this issue!
