### ISSUE TITLE
Unknown blueprint: page-object-helper

### ISSUE THREAD

**Issue by DenQ** [san650/ember-cli-page-object#173]
Hello.
When I run in terminal:
`ember g page-object-helper login
`

I got an answer:
`Unknown blueprint: page-object-helper`

In file https://github.com/san650/ember-cli-page-object/blob/master/app/blueprints/page-object-helper.js#L1 imported not existing module.

**Comment by san650** [comment]
Hi @DenQ , thanks for reporting this error.

The blueprint was removed for the 1.0 but for some reason we didn't delete app/blueprints/page-object-helper.js file. Maybe we can bring it back and make it generate a dummy descriptor. @DenQ @juanazam @jeradg thoughts?

Also, page object helpers are just functions or descriptors if you need more advanced functionalities. 

Here's an example of a custom descriptor (I think we don't have documentation for this on the http://ember-cli-page-object.js.org/ site yet.)

```js
import { findElement } from 'ember-cli-page-object';

export default function disabled(selector, options = {}) {
  return {
    isDescriptor: true,

    get() {
      return findElement(this, selector, options).is(':disabled');
    }
  };
}
```

I usually put my page object's helpers on /tests/pages/helpers/, you can do the same without the blueprint for now.

**Comment by jeradg** [comment]
@san650: I like the idea of having a generator for properties/actions/descriptors. We could even have a couple of different blueprints for different custom property/action use cases.

**Comment by juanazam** [comment]
http://ember-cli-page-object.js.org/docs/v1.3.x/migrating#customhelper
 
I'm :+1: on creating the descriptor blue print.
