### ISSUE TITLE
Addon's file structure

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#174]
The project is growing a lot, lot of new properties and each property now has two modes, one for acceptance and another one for integration. The source code is having a lot of repeated code (Codacy is not happy with this!) 

So maybe it's time to start thinking about restructuring the internals of the project a bit better to make it easier for people to contribute and for maintainers to, we'll maintain it.

I'm proposing a change in the file structure to make it easier to find elements and to hide private files from being required by apps.

This is what I have in mind

```
.
├── addon
│   ├── -private
│   │   ├── actions
│   │   │   ├── click-on-text
│   │   │   │   ├── acceptance.js
│   │   │   │   └── integration.js
│   │   │   ├── clickable
│   │   │   │   ├── acceptance.js
│   │   │   │   └── integration.js
│   │   │   ├── fillable
│   │   │   │   ├── acceptance.js
│   │   │   │   └── integration.js
│   │   │   ├── click-on-text.js
│   │   │   ├── clickable.js
│   │   │   ├── fillable.js
│   │   │   └── visitable.js
│   │   ├── ...
:   :   :   ...
│   │   ├── helpers
│   │   │   └── find.js
│   │   └── create.js
│   └── index.js
└── app
    └── index.js
```

and for tests

```
tests/
    └── unit
        ├── acceptance
        │   ├── click-on-text-test.js
        │   ├── clickable-test.js
        │   ├── ...
        │   └── visitable-test.js
        └── integration
            ├── click-on-text-test.js
            ├── clickable-test.js
            ├── ...
            └── fillable-test.js
```

What do you think?

**Comment by jeradg** [comment]
@san650: I agree in principle, except for the testing file structure. What's the thinking behind nesting `integration` and `acceptance` under `unit`?

**Comment by san650** [comment]
@jeradg our unit tests aren't so unit by strict definition. We need to create an application before each test so Ember's test helpers are registered in the global context (e.g. `fillIn()`). Right now our "unit" tests test the `acceptance` part of the property but not the `integration` part of it.

I would like to have a test structure that reflects this, I like to call these tests "unit" because we test only one property at a time and we test it well, also they run so fast that it doesn't make sense to avoid the dependencies.

But for the `integration` part of the properties we're not testing them so thoroughly, having a folder structure that forces us to have both sides of the property tested is a win (I think).

Maybe the folder structure I proposed for the tests is counter intuitive and there are better structures. Let's brainstorm a bit about it. What do you think?

**Comment by san650** [comment]
Done by #222
