### ISSUE TITLE
Using `triggerable` and other actions with dynamic segments

### ISSUE THREAD

**Issue by dgroverWintac** [san650/ember-cli-page-object#187]
Thanks for this awesome library!

I downloaded one of the recent commits to get access to `triggerable`, and it's working great. I'd love to be able to write a dynamic page object method that leverages all the existing code in `triggerable`.

Here's the sort of thing I'm after:

```js
// tests/my-test.js
page.visit()
  .doubleClickEventInstance('my new event')
  ...
```

and my first attempt:

```js
// pages/po.js
import { triggerable } from 'ember-cli-page-object/actions/triggerable';

export default create({

  doubleClickEventInstance(title) {
    return triggerable('dblclick', `.fc-day-grid-event:contains(${title})`),
  }
});
```

but it seems that the included actions aren't just functions, but return objects with `get` methods.

Can you think of an easy way to accomplish what I'm after?

**Comment by san650** [comment]
Hi @dgroverWintac 

The `triggerable` function returns a Descriptor, it doesn't fire the action per-se. To execute an action just use Ember's default test helper [`triggerEvent`](http://emberjs.com/api/classes/Ember.Test.html#method_triggerEvent)

```js
// pages/po.js
export default create({

  doubleClickEventInstance(title) {
    triggerEvent(`.fc-day-grid-event:contains(${title})`, 'dblclick');

    return this;
  }
});
```

The `return this` allows you to chain calls to other actions.


Hope this helps.

**Comment by san650** [comment]
@dgroverWintac I'm closing this issue as I think you're question was addressed.

If you still have questions about this or think it wasn't addressed, please feel free to reopen it.

Thanks!
