### ISSUE TITLE
Upgrade ceibo to 2.x

### ISSUE THREAD

**Issue by nbibler** [san650/ember-cli-page-object#188]
The 1.1.0 release of ceibo has a `const` defined in it which was [fixed in the 2.x release](https://github.com/san650/ceibo/commit/dc1a9e321eb79e1be2316ab8c08978e87c0cbc93). As such, browsers that don't support `const` cannot load the application in development or test mode.

**Comment by san650** [comment]
Hi @nbibler, the addon is using ceibo@2.0.0 since v1.3.0.

Are you having some issues with it? Does the dependencies upgraded correctly when you upgraded ember-cli-page-object to v1.3.0?

**Comment by nbibler** [comment]
Running `ember install ember-cli-page-object` seems to only update the `package.json` to the latest version (1.3.0). The `bower.json` remains unchanged with `"ceibo": "1.1.0"`.

**Comment by nbibler** [comment]
Hmm... perhaps the Bower dependency was added by a different addon! I'll investigate and get back to you!

**Comment by nbibler** [comment]
So, I think a few things might've happened:

The page object library was originally installed at 1.1.0, which installed the ceibo bower dependency at 1.1.0. When upgrading to 1.3.0 of ember-cli-page-object, the blueprint was removed which originally added the bower dependency. However, because the blueprint was removed, nothing cleaned up the ceibo dependency from the bower.json file (whether this is your responsibility or not to remove it is certainly a grey area).

So, using 1.3.0 after an upgrade still had a ceibo 1.1.0 dependency in bower. Manually removing that appears to correct the issue after the 1.3.0 upgrade.

Maybe? Plausible? :-D

**Comment by san650** [comment]
We're not removing the old bower dependency and we should. Maybe we can create a different bug for that.

"Remove Ceibo as bower dependency on upgrade" or something like that. @nbibler can you open that issue?

**Comment by nbibler** [comment]
I can... I just worry if it will errantly remove a dependency that someone else might've added to Bower. Hard to say if "ceibo" was added for page object or something else after the fact. :-/
