### ISSUE TITLE
Restrict ceibo loading to test mode only

### ISSUE THREAD

**Issue by nbibler** [san650/ember-cli-page-object#189]
The `index.js` loads ceibo in non-production environments. However, there's no reason to load it in development mode, as this is a testing library.

```javascript
  _shouldIncludeFiles: function() {
    return this.app.env !== 'production';
  }
```

Presumably, `_shouldIncludeFiles` should only be `true` when `this.app.env === 'test'`.

**Comment by san650** [comment]
Hi @nbibler, thanks for taking the time to open the issue.

When you run the development server in `development` mode you can run your tests by accessing to http://localhost:4200/tests See http://ember-cli.com/user-guide/#create-a-new-project

Also, take a look at this issue #126 😄

**Comment by nbibler** [comment]
Hmm.. Thanks for getting back, @san650!

My understanding - which might very well be wrong! - is that accessing `/tests` in Ember CLI's development mode _happens to work_ for now, but isn't necessarily supported behavior.

**Comment by san650** [comment]
@nbibler Didn't know that! Looking at the ember-cli code it looks like an intended feature (one that I use all the time 😄 ) and it's documented on ember-cli's site

Can you point to an ember-cli issue, PR or RFC that explains this?

**Comment by nbibler** [comment]
I can't! I've been looking. :)

Maybe I'm wrong! It wouldn't be the first time, for sure. I'll reopen this ticket if I happen to come across whatever caused me (us!) to think this was the case.

Thanks again!
