### ISSUE TITLE
Test failures when running tests from the dummy app

### ISSUE THREAD

**Issue by migbar** [san650/ember-cli-page-object#193]
Tests that require ```ember-template-compiler.js``` fail on ```master``` when I run them from the dummy test app in the browser (as in ```localhost:4200/tests```)

Error message: 
```Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.```

```
➙  ember -v
version: 2.4.2
node: 4.3.0
os: darwin x64
```

All tests pass if I run in test environment (as in ```ember test --server```)

I understand that most people run their tests the latter way, but In case anyone wants to run them from the browser, is there a downside to just including the ```ember-template-compiler.js``` in the ```ember-cli-build``` regardless of what environment we are running?

**Comment by san650** [comment]
@migbar Shouldn't be a problem to always include the ember-template-compiler file regardless of the environment. I'll take a look at the PR later today.

Thanks for contributing
