### ISSUE TITLE
Iterating over collections broken

### ISSUE THREAD

**Issue by simonihmig** [san650/ember-cli-page-object#196]
It seems I cannot iterate over collections without using an explicit index.

Look at the following example:
```js
      console.info('for-loop');
      for (let i=0; i < page.categories().count; i++) {
        let category = page.categories(i);
        console.log('meta', category.__meta.key);
        console.log('headline', category.headline);
      }

      console.info('for-of-loop');
      for (let category of page.categories()) {
        console.log('meta', category.__meta.key);
        console.log('headline', category.headline);
      }
```

This is the output I get:
![image](https://cloud.githubusercontent.com/assets/1325249/15863082/fa5e0af2-2cd1-11e6-9118-bbc189cfd3ee.png)

The first for-loop is working fine, but there is something broken with the for-of loop: `__meta.key` is `undefined(0)`, and the `[data-test-selector="product-categories"]` selector is duplicated (this is from categories.scope, see below). The same happens when I change the for-of to a forEach construct:

```js
    page.categories().toArray().forEach((category) => {
        console.log('meta', category.__meta.key);
        console.log('headline', category.headline);
      });
```

My page object: (`selectElement` is just a helper function returning a DOM selector)

```js

export default create({
  visit: visitable('/de/shop/configurator/:id'),

  categories: collection({
    scope: selectElement('product-categories'),
    itemScope: 'section',
    item: {
      headline: text(selectElement('product-category-name')),
      products: collection({
        itemScope: selectElement('product'),
        item: {
          modelId: attribute('data-test-model'),
          name: text(selectElement('name'))
        }
      })
    }
  })

```

**Comment by san650** [comment]
@simonihmig Thanks for the detailed bug reporting, I'll take a look at it later today or tomorrow

**Comment by san650** [comment]
@simonihmig I'm working on a fix for this issue, see #197

Can you try to reproduce the error using the `remove-item-property-from-collection` branch?

To use this branch you need to change you package.json like this:

```
"ember-cli-page-object": "san650/ember-cli-page-object#remove-item-property-from-collection"
```

Thanks!

**Comment by simonihmig** [comment]
Thanks for your quick response. I tried that, but unfortunately without success. :(

It seems the collection must have a scope property for that error to appear. I saw that you have a test present with a for-of-loop. I just added some other tests, each with a collection with a scope property, the first with a for-loop, then a for-of-loop and a forEach. The first passes, the other two fail, just as they did within my app.  

Here is the commit: https://github.com/simonihmig/ember-cli-page-object/commit/98ef487e1677e36ab9cebe9ffa460273478bc631

I did not submit a PR, as it would add failed tests and thus a broken build. But if you like me to do so (maybe to some other branch than master), then give me a note!

**Comment by san650** [comment]
@simonihmig It would be great if you could open a PR with the failing tests. Can you rebase your branch with `remove-item-property-from-collection` branch?

I'll try to work on this a bit tomorrow

**Comment by simonihmig** [comment]
@san650 Added PR. PR target is your `remove-item-property-from-collection` branch, not master, hope that is what your intention was as well!

**Comment by san650** [comment]
@simonihmig thanks for the test cases, I've changed a bit how we generate the collection's items when using the iterator. Now it should be working fine.

Can you take a look at the PR? Does it fixes your app?

**Comment by simonihmig** [comment]
Thanks @san650 for the quick fix! I can confirm this works now without any issues! :)
