### ISSUE TITLE
[Proposal] an ability to interact with dynamically rendered fields 

### ISSUE THREAD

**Issue by ro0gr** [san650/ember-cli-page-object#198]
### The Problem

As far as I can see currently page objects are supposed to work only with static page layouts. I mean you as a developer should define all the possible page fields at the page object's design time.   

Let's say you have a fieldset which contains some controls. Each time user changes some dropdown  completely new controls are re-rendered. [Here](https://ember-twiddle.com/51d46fcbca54bc0e784ef77a127f50a0) is an example of what am I talking about.

Now if we need to write tests which depend on several dropdown states I can see only two options:
- declare all the possible fields in the page object
- implement page objects for each of dropdown states which is almost the same as the first ption

both variants seems redundant. It requires lots of copy-paste and pollutes the page object:

``` js
create({
  field1State1: fillable('.control[name="field1"]'),
  field2State1: selectable('.control[name="field2"]'),
  field1State2: fillable('.control[name="field1"]'),
  field2State2: clickable('.control[name="field2"]'),
  field3State2: selectable('.control[name="field3"]')
})
```
### Proposal

I think we may need to provide a way for `selectors` not to be completely hard-coded in the page objects. It can contain something like selector template string which can be compiled when it accessed from the test. 

An ideal(from my optimistic perspective) api may be something like this:

``` js
const page = create({
  // I use "&" as a placeholder to be replaced with an actual value 
  // when template compilation happened. Probably it should be something another
  // but I like analogy with `less`|`sass` here ;) 
  templatedInput: fillable('.control[name="&"]'),
  templatedCheckbox: clickable('.control[name="&"]'),
  templatedDropdown: selectable('.control[name="&"]')
});

page.visit()
    .templatedInput('field1', 'some text')
    .templatedCheckbox('field2')
    .templatedDropdown('field3', 'option5')
```

It allows us to significantly reduce lines of code and makes page object much more flexible.
### Drawbacks

I suspect an implementation of example above may require lots of work and rewriting existing methods.
### Alternatives

I've [tried to play](https://github.com/ro0gr/ember-cli-page-object/commit/72194a86eed305b6cb03b748d1fe6e280362ae2a) with this idea and not touching an original action implementations. It looks like this:

``` js
const page = create({
  templatedInput: lazyProp(fillable, '.control[name="&"]'),
  templatedCheckbox: lazyProp(clickable, '.control[name="&"]'),
  templatedDropdown: lazyProp(selectable, '.control[name="&"]')
});
```

but different of the actions/queries/predicates... have different signatures

``` js
clickable(selector, options)
triggerable(event, selector, options)
attribute(attributeName, selector, options)
...
```

which complicates an implemetation.

I believe there may be some other ways. I would like to explore it and help with implementation if you are interested. 

Please let me know your thoughts on this.

**Comment by san650** [comment]
Thanks @ro0gr for opening this issue. This is definitely a missing feature that we would like to address.

First of all, I like the solution you're proposing but I'm thinking how to make it even more flexible.

Let me share with you some of my thoughts regarding to this:

For quite some time now I've been thinking what's the best approach to fill lots of fields. Another issue that it's somewhat related is that there are several addons that try to avoid the coupling between application HTML and testing CSS selectors.

Here are same examples of what I'm referring to:

* __ember-test-selectors__ generates selectors like `[data-test-foo]` from `<span data-test="foo">`. See https://github.com/simplabs/ember-test-selectors
* __ember-hook__ generates selectors like `[data-test="foo"]` from `<span data-test="foo">`. See https://github.com/Ticketfly/ember-hook

Apart from that, when writing forms people usually follow some conventions or common patterns like

* Common patterns from HTML `<input name="givenName">` or `<input id="givenName">`
* __ember-form-for__ generates ids like `<input id="form123_givenName">` from `{{form-field "givenName" ...}}`. See https://github.com/martndemus/ember-form-for/blob/755e9bb34be023510a069ea7ff98c203449208fb/tests/integration/components/form-field-test.js#L68-L69

Reading about your idea it occurred to me that we could solve all these issues by adding some kind of hooks to page object actions.

Let's say that you could define a hook `resolveActionSelector` at the page object's root level that allowed you to do any transformation on the actions' selectors. Let's say also that we add a new optional parameter to every action (the first parameter for convenience) that is passed to that hook. Then you could do something like this:

A form

```html
<form>
  <label for="userName">User Name</label>
  <input id="userName">

  <label for="password">Password</label>
  <input id="password" type="password">

  <button>Submit</button>
</form>
```

A test

```js
import ...;
...

var page = create({
  visit: visitable('/login'),

  fillIn: fillable('#&'),

  hooks: {
    resolveActionSelector(template, dynamicValue) {
      if (/&/.test(template)) {
        return template.replace(/&/, dynamicValue.camelize());
      }

      return template;
    }
  }
});

test('login failed', function(assert) {
  page
    .visit()
    .fillIn('user name', 'John');
    .fillIn('password', 'secret');
    .submit();

  andThen(function() {
    assert.equal(currentPath(), 'foo.bar');
  });
});
```

The hook `generateActionSelector` would be called every time you call an action in your test giving people the opportunity of changing it.

This way we could generate all the above selectors just by providing a function. It's really easy to generate all the flavors of CSS selectors given `page.fillIn('given name', 'John');`

* `[data-test-given-name]`
* `[data-test="givenName"]`
* `.control[name="GivenName"]`
* `#form123_givenName`

This solution assumes that we have to change `fillable` helper to receive up to two values.
* if one parameter is provided, use that parameter as the value to fill in the textbox
* if two parameters are provided, use the first one to resolve the selector and the second one to fill in the textbox

This way we keep backward compatibility for all actions.

As always, this is just an idea, let's continue the discussion and see what others think about the proposals cc/ @juanazam @jeradg


PS: Sorry my english, if something is not clear, please, let me know.

**Comment by ro0gr** [comment]
@san650 I'm glad you are not opposed to extend an initial API for the actions to support additional param.
Anyway now I'm concerned about the [queries](http://ember-cli-page-object.js.org/docs/v1.4.x/api/queries) and [components](http://ember-cli-page-object.js.org/docs/v1.4.x/components) APIs. There are just getters so it's impossible to pass arguments in it from the test. 

So at this point we have `actions`, `predicates` and `collections` which potentially may be templated and `components` and `queries` which can't.

Reading #105 I came up with an idea. What if it would be enough to provide selectorTemplates  functionality only on the `Component` level and do not touch the rest of API?

We can try to provide a new abstraction for `dynamic components` whose selectors evaluated in the runtime and all the others(`actions`, `predicates`,...) may remain untouched at least for the initial implementation:
```js
var page = create({ 
  visit: visitable('/login'),
  // Yes, naming is hard :)
  superInput: dynamicComponent({
    scopeTemplate: '#&',
    fillIn: fillable(),
    value()    
  })
});
...
page
  .visit()
  .superInput('login').fillIn("username");

andThen(function() {
  assert.equal(page.superInput('login').value, "username");
})
```
If we go this way it allows us to:
 - leave current API untouched(only add new Component class)
 - concentrate on actual API design instead of fighting with exisiting code base :)
 - cover most of use cases

This idea is very raw, it just came to my mind. Probably need to think about it more. Any visible drawbacks? 

-
As for the `resolveActionSelector` proposition. I can't come up with a real use case which may need such kind of hook. If somebody needs to use dynamic `userName` or `UserName` key why not just to past it directly from the test?
```js
    .fillIn('userName', 'John');
    // or
    .fillIn('UserName', 'secret');
```
I believe such kind of hook is too powerful:
 - you can access(and modify) `template` which you really don't care about
 - you should compile template on your own which reduces declarative nature of `ember-cli-page-object`. 

Also adding of such kind of hook may complicate the debug process of your test. So I'm in favor of  some built-in support for selectors compilation. And if we eventually need keys transformations we can try think about less verbose hook like:
```js
hooks: {
  transformFieldName(fieldName) {
    return fieldName.camelize());
  }  
}
```

**Comment by san650** [comment]
I'll think a bit more about this, I like you're suggestion about `dynamicComponent` although I would look for a better name 😛 

The `dynamicComponent` helper is not hard to implement using the public API, you can start using this in your project today!

```js
function dynamicComponent(object) {
  return {
    isDescriptor: true,

    value(replacement) {
      let definition = {
        ...object,
        scope: object.scopeTemplate.replace(/&/, replacement)
      };

      return create(definition, { parent: this });
    }
  };
}
```

```js
test('dynamic component', function(assert) {
  fixture('Hello <span id="an-id">world!</span>');

  let page = create({
    foo: dynamicComponent({
      scopeTemplate: '#&',

      bar: text()
    })
  });

  assert.equal(page.foo('an-id').text, 'world!');
});
```

We should consider adding something like this to the addon, let me think about this a bit more, I would like to do some experiments to see if we cover all the scenarios I pointed in my first comment.

Please, let me know if you start using the helper I described here and how _it feels_ using it in a real project.

**Comment by ro0gr** [comment]
Thank for the guidance @san650. Will keep you informed.
I like an idea to implement a prototype for this as an addon. It will allow me to start use it asap on my real project. 
If we satisfied we can always merge it or just throw this idea away if not :innocent:

**Comment by ro0gr** [comment]
Started working on it [here](https://github.com/ro0gr/ember-cli-page-object-component).

Just the first thought. Can we safely name it a [`component`](https://github.com/ro0gr/ember-cli-page-object-component/blob/master/tests/pages/registration.js#L6)? I know it intercepts with existing components but existing components are pure hashes and this one is a function. 

I ask because `dynamicComponent` is a really bad name as for me.

**Comment by san650** [comment]
@ro0gr That's awesome! It's a really nice way to experiment with new features fast and easy.

> Can we safely name it a component?

We used to have a `component` property in the 0.X branch, we don't have that anymore so I guess it's quite safe to call it component.

I'm ok with that name although it can be confusing for people that want to start using the new addon because we refer to PageObject's nodes as components throughout the project and the documentation, so I guess is your call 😄 

Just an idea, you could name the addon and new the new property as `template` because you're defining a component template after all.

```js
import { create, text } from 'ember-cli-page-object';
import { template } from 'ember-cli-page-object-template';

var page = create({
  button: template({
    scope: '#&',

    label: text()
  })
});
```

And you could override the default behavior of `scope` to support the template.

Just my 2¢

**Comment by ro0gr** [comment]
@san650 Thank you for feedback!

Unfortunately I still didn't have a chance to test this approach with a real application. Hope I'll do it next week. Anyway I'm going to cover by tests each corner case which I can imagine to check if everything works seamlessly. 
 
I very like your idea just to add template support for `scope` property and not to extend `options` interface.

-

It's quite funny but I'm still not fully satisfied with any name for this thing. I'll try to summarize all the existing candidates:
 - `dynamicComponent()` - an attempt to say to a consumer that it's something very close to existing `component` concept but has some dynamic nature. Unfortunately it's not clear from the name which part of component is exactly dynamic and what does it mean at all :-1: 
 - `template()` - I also have thought about this name at the very start of my thinking. It solves name collision concern for existing `component` API. But I have some doubts about this name:
  - I feel like `.control-&` is more similar to template than what's we are trying to do here.
  - What if once we want to add `template` for let's say `collection`(just in theory)? how do we name it?
 - `componentTemplate()` - takes the best parts from `component()` and `template()` but again:
  - I still think `template` may not describe this concept in the best way(possibly I'm wrong)
  - If we eventually want to add support for templates for collection we should implement new `collectionTemplate()` instead of just adding templates support to `collection().scope` property     
 - `component()` - Like you've said the main drawback here is a name collision with existing `component` concept. Anyway I think `component()` may be considered as the same thing as `component` but due to the callable nature it now supports templated `scope`. Also being callable `component` becomes more similar to the `collection()` API.   

So currently my personal favorite is a `component()` but I would definetly be ok with `template()`, `componentTemplate()` or any better name if it comes to us :smirk_cat:   

cc/ @juanazam @jeradg

**Comment by juanazam** [comment]
@ro0gr thanks for proposing this enhancement, I believe this is great and opens a new way of building Page Objects that can be very handy. I understand this is not the regular case for all applications so I'm :+1: on creating a separate property to handle this. I see that naming this property has become a real pain so here is my proposition.

What we are trying to build here is a component that can be templated right? So I think we should call it `templatedComponent`. 

@ro0gr @san650 What do you guys think?

**Comment by jeradg** [comment]
I like the name `templatedComponent`, but is it a little verbose? Definitely the most descriptive though.

**Comment by juanazam** [comment]
If `templatedComponent` is not enough, I think I would go for `templated` 😄

**Comment by ming-codes** [comment]
ExtJS has this idea of a component query. It's similar to CSS but query against component type and it's attribute value (component attribute, not HTML attribute). I think it's a pretty good idea.

**Comment by ro0gr** [comment]
It can be achieved with `collection` + a custom finder method, like:

```js
{
  field(id) {
    return this.fields.toArray().find(f => f.id === id);
  },

  fields: collection('input[name]', {
    id: attribute('name')
  })
}
```

Closing.
