### ISSUE TITLE
1.4.0 Changelog documentation missing

### ISSUE THREAD

**Issue by Q2KJordan** [san650/ember-cli-page-object#201]
v1.4.0 is published but looking in CHANGELOG.md there's no info available for what's changed from v1.3.0.

**Comment by juanazam** [comment]
@Q2KJordan have you checked the releases section of the addon? https://github.com/san650/ember-cli-page-object/releases/tag/v1.4.0 we usually write about changes on each release notes.

**Comment by san650** [comment]
We should update the release checklist so we don't forget to update the changeling.
