### ISSUE TITLE
`collection` now mutates its input

### ISSUE THREAD

**Issue by dfreeman** [san650/ember-cli-page-object#207]
It looks as though [this commit](https://github.com/san650/ember-cli-page-object/commit/78fbb2d48370d35ba8f13fcd00ae1d36670a0e91) changed the `collection` helper so that it now deletes keys on its input hash, which broke several of our page objects. Up to 1.4.0, we had been sharing the POJOs for such definitions among related page objects to make it easy to refine e.g. the items in the collection for more specific use cases.

We could move to using factory functions instead so that every definition is guaranteed fresh input, but simple `...` object spread had been working quite nicely to this point, and it was surprising to me that any of the helpers would mutate their input.

[This twiddle](https://ember-twiddle.com/6f7689d10ec6877e484f9f0a0ab2b842?fileTreeShown=false&numColumns=3&openFiles=tests.integration.components.my-component-test.js%2Ctemplates.components.my-component.hbs%2Ctwiddle.json) shows an example that fails in 1.4.1 because of this change, but passes if you switch the dependency in `twiddle.json` to 1.4.0.

**Comment by san650** [comment]
@dfreeman thanks for the detailed bug report and sorry I broke your page objects 😞 .

As discussed on slack, the idea is that we shouldn't mutate the definition of the page objects, I'm almost sure we're cloning the definitions for `create` but not for `collection`.

[Here](https://github.com/san650/ember-cli-page-object/blob/dbf823cb01cbeeb115e0b0645168718031e59383/addon/collection.js#L206-L214) we should do something like `var definition = $.merge({}, definition, true);` _similar_ to what we do for `create` [here](https://github.com/san650/ember-cli-page-object/blob/dbf823cb01cbeeb115e0b0645168718031e59383/addon/create.js#L112-L114). Also, we should add some tests so it doesn't break again.

**Comment by san650** [comment]
@dfreeman can you test #208 in your project to confirm that it fixes all the issues?
