### ISSUE TITLE
Document folder conventions

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#21]
One of the ideas @juanazam and I have is to have some conventions on where to generate the object pages.

We would like to propose and document these conventions so everyone can take advantage of them.

__Edit: take a look at #27 and #32__

## Folder structure

1. Put your Page Objects in `<root>/tests/pages/` folder
2. Put you custom components in `<root>/tests/pages/components/` folder

An example could be
```
myApp/tests
└── pages
    ├── team.js
    ├── users.js
    ├── users-add.js
    └── components
        ├── search-box.js
        └── gear-menu.js
```

## Naming conventions (?)

This is something we didn't discuss yet and we would like to hear ideas. 

For simple routes like `users.index` it's easy to pick a name for the page object `<root>/tests/pages/user.js`, but when you have complex nested routes it's no so trivial to pick a name. It would be great to have some guidelines.

**Comment by juanazam** [comment]
:+1: A good questions would be were to put those components which the developer wants to separate from the page to make it smaller but are not re used elsewhere, the components general folder might become a bit messy. I guess we could apply naming conventions or that case (as well as in pages themselves for nested routes).

**Comment by san650** [comment]
#35 adds the last two blueprints needed to complete this feature.
