### ISSUE TITLE
Go to source code links are broken in the website

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#218]
Each method in the API documentation has a link to the source code, right now those links are broken. See http://ember-cli-page-object.js.org/docs/v1.4.x/api/helpers#getcontext

Expected URL
https://github.com/san650/ember-cli-page-object/blob/f6764e1741c7d2964c1cba26ae375c672ad45d02/addon/helpers.js#L300-L309

Actual URL
http://ember-cli-page-object.js.org/docs/v1.4.x/api/undefined/blob/f6764e1741c7d2964c1cba26ae375c672ad45d02/addon/helpers.js#L300-L309

**Comment by jeradg** [comment]
@san650: Fixed and deployed to the docs site.

However, I'm wondering how the error happened in the first place. I'm especially wondering how it was possible to generate the documentation after the folder structure was changed, moving all of the properties into `addon/-private/properties`. I'm guessing the error occurred during a deploy of the v1.4.0 docs, and then the v1.4.0 docs were just copied to v1.5.0. Does that sound about right?

I'm going to open a separate ticket to update `docs.js` to be able to parse docs from the new directory structure, which it currently can't.

**Comment by san650** [comment]
I broke it 😞  and didn't have the time to fix it accordingly so I just copied the folders. Thanks for taking the time to look into this.
