### ISSUE TITLE
Pause test on error option when running under QUnit

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#226]
It would be great to have an option on QUnit to pause the test execution when the page object fails to find an element in the DOM.

We could add a checkbox in QUnit's index.html page so we could activate the feature when that option is selected.

<img width="473" alt="screen shot 2016-08-02 at 2 35 45 pm" src="https://cloud.githubusercontent.com/assets/1234607/17338607/70d8fb0c-58be-11e6-9bd7-3b9b219b0980.png">

The idea is that when you're working on a test, sometimes the selectors are incorrect and would be really useful if the tests stops with the rendered page and all the information about the missing page object property/selector in the javascript console.

**Comment by jeradg** [comment]
@juanazam, are you interested? I'm happy to take this on.

**Comment by fedekau** [comment]
@jeradg Hi! I started looking how to implement this as my first contribution to the project, If you are ok with that I would like to keep working on that :)

**Comment by san650** [comment]
This will be implemented as a separated addon
