### ISSUE TITLE
Update `docs.js` to parse new addon structure

### ISSUE THREAD

**Issue by jeradg** [san650/ember-cli-page-object#228]
The addon structure recently changed, moving files into `addon/-private`. The docs generator needs to be updated to correctly parse files in the new structure.

**Comment by jeradg** [comment]
@san650 @juanazam: Are we OK with having the documentation for every property on a single page? I'm personally OK with that -- I think the old structure was confusing.

**Comment by san650** [comment]
@jeradg YES! that's one of the points I wanted to talk with you and Juan about the site redesign I'm considering.

People had told me that they find it difficult to find what they're are looking for and part of that is because of the grouping.

Thanks for taking care of this!

**Comment by jeradg** [comment]
Good -- that answer is also much easier to implement! :smile:

**Comment by jeradg** [comment]
Working on a PR: https://github.com/san650/ember-cli-page-object/pull/252

**Comment by jeradg** [comment]
Closed (a while ago!) by #252.
