### ISSUE TITLE
integration with Ember Power Select

### ISSUE THREAD

**Issue by Pasikonik** [san650/ember-cli-page-object#229]
Is it possible to use ember-power-select test helper in this addon?
I found this:
https://gist.github.com/migbar/3d961ddb7aaad1588949
but I'm not sure how integrate it with page-object

The EPS helper: 
http://www.ember-power-select.com/docs/test-helpers

**Comment by san650** [comment]
@Pasikonik you can use the ember-power-select helpers by adding a function to the page object

e.g.
```js
var page = create({
  visit: visitable('....'),

  selectChoose(optionText) {
    // using the ember-power-select helper here
    selectChoose('.a-selector', optionText);
    return this;
  }
});
```

and in the test you can do

```js
page.visit().selectChoose('foo');

andThen(function() { ... });
```

Note that we're returning `this` in the function to allow chaining of other actions.

That's the simplest integration possible between ember-cli-page-object and ember-power-select. It works but it has some limitations, for example, it doesn't resolve the scope automatically (the CSS selector is hardcoded).

@migbar gist is an example of how to improve the integration between both addons by defining a page object descriptor.

@Pasikonik let me know if this example works for you or if you find any issue. I can code a better example/code if needed.

**Comment by Pasikonik** [comment]
example works perfectly!
thanks a lot :)

**Comment by sukima** [comment]
This only works for acceptance tests where you have a full application and the async test helpers. integration tests can not use this as far as I can tell.

**Comment by san650** [comment]
@sukima can you open a separated issue for this? If I have time today I'll try to find a solution that works on integration tests.

**Comment by sukima** [comment]
That is what I ended up doing:

```js
import PageObject, { findElementWithAssert }
  from 'ember-cli-page-object';
import { nativeMouseDown, nativeMouseUp }
  from '../../../tests/helpers/ember-power-select';

export const FilterMultiSelect = {
  scope: '.ui-filter-multi-select',

  openPicker() {
    let $element = findElementWithAssert(
      this,
      '.ember-power-select-trigger'
    );
    nativeMouseDown($element.get(0));
    return this;
  },

  pickOption(text) {
    let $element = findElementWithAssert(
      this,
      '.ember-power-select-option',
      {contains: text}
    );
    nativeMouseUp($element.get(0));
    return this;
  },

  pick(text) {
    this.openPicker().pickOption(text);
    return this;
  }
};

export default PageObject.create(FilterMultiSelect);
```

Thanks.
