### ISSUE TITLE
Component lookup

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#23]
If we go with #21 and decide that custom components go in `tests/pages/components` folders, we can actually try to load the components by name in the page object definition.

Let's say we have a component `tests/pages/components/context-menu.js`, we could load it automatically from the page definition:

```js
var page = PageObject.build({
  visit: visitable('users'),
  contextMenu: component('context-menu'),
  // ...
});
```

We can overload the `component` attribute helper so when it receives only a string parameter it can lookup a component with the name `context-menu` in the folder `tests/pages/components`.

**Comment by juanazam** [comment]
Sounds great!

**Comment by san650** [comment]
Not going to happen anytime soon. Closing the feature request for now.
