### ISSUE TITLE
'isVisible' without iterating over collection

### ISSUE THREAD

**Issue by Ronald-Gynzy** [san650/ember-cli-page-object#239]
Hi,
Very nice plugin. I have a question. I would like to use the isVisible without iterating over a collection every time. I would like to do something like this.

```
activityVisible: isVisible('.title h5', {
    scope: '.activity-component'
}),
```

Actually it would be nice if it works the same like the `clickOnText()`. 

```
clickOnActivity: clickOnText('.title h5', {
    scope: '.activity-component'
}),
```

Just want to check if a selector with a given text, is visible. Is that possible or is there a other way i can do something like this?

Thank you!

**Comment by juanazam** [comment]
Hi @Ronald-Gynzy,

Lets say that you have a page with with a title with class `main-title`. The simplest way to check that would be:

Definition of PO
```js
const page = PageObject.create({
  scope: '.my-page',
  mainTitleIsVisible: isVisible('.main-title')
})
```

Usage:

```js
page.mainTitleIsVisible // returns true or failse if element ".main-title" is visible.
```

Alternative:

```js
const page = PageObject.create({
  scope: '.my-page',
  mainTitle: {
    scope: '.main-title'
  }
})
```

Usage

```js
  page.mainTitle.isVisible // returns true if element with selector ".main-title" is visible.
```

As you can see, we never defined is visible for the main title component in the second definition. The addon automatically include some properties to every component. Documentation can be found here: http://ember-cli-page-object.js.org/docs/v1.5.x/components#default-attributes

**Comment by Ronald-Gynzy** [comment]
Thanks for your response! I found out that there is a possibility to collect items with a collections. Those to combined, made it al easier.
