### ISSUE TITLE
Option to set testContainer on page/component/collection?

### ISSUE THREAD

**Issue by mattmcmanus** [san650/ember-cli-page-object#243]
I see that there is support for overriding the `testContainer` on specific items on a page. However, I have several collections/components that show up in a separate `testContainer` and it's making the page object a bit sloppy, and it's impossible to use the `collection` method (as far as I can tell). 

Is there a way that you can provide a test container in `create` or `collection` that all subsequent attribute would obey?

**Comment by san650** [comment]
@mattmcmanus it would be really useful indeed.

I'll try to code something next week but if anybody wants to work on this would be great, I can give you some pointers on how to implement it.
