### ISSUE TITLE
[Site] Document ES7 await support

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#25]
It would be great to document the support of `await` on actions

**Comment by san650** [comment]
We could add an articles section to the site and add this kind of information there, like a mini `how to`

**Comment by brancusi** [comment]
:+1:

**Comment by san650** [comment]
This will be published with the site redesign. You can also read about this topic here https://wyeworks.com/blog/2016/6/13/using-async-and-await-with-ember-cli-page-object/
