### ISSUE TITLE
Reference error on basic implementation

### ISSUE THREAD

**Issue by vigpatrick** [san650/ember-cli-page-object#251]
I used the documentation to do a simple test to test the current path. I've generate the file using the cli and import the page into my acceptance test. Every time I run the test they say that visit is undefined.

`// tests/pages/projects.js`
`import {`
`  create,`
`  visitable`
`} from 'ember-cli-page-object';`

`export default create({`
`  visit: visitable('/projects')`
`});`

`// tests/acceptance/projects-test.js`
`import { test } from 'qunit';`
`import page from 'log-book/tests/pages/projects';`

`test('Visit projects', function(assert) {`
` page`
 `   .visit();`

`  andThen(function() {`
`    assert.equal(currentURL(), '/projects');`
`   });`
`});`

anyone know why i got this issue

**Comment by san650** [comment]
@vigpatrick that's strange. What ember, ember-cli and ember-cli-page-object versions are you using?

I've created a quick example on ember-twiddle and seems to be working fine: https://ember-twiddle.com/458b0ed1f5e7554bd95e7e91cad895f6?openFiles=tests.acceptance.hello-test.js%2C&route=%2Fhello

Can you try to create a test like the example? and see if it fails. You can also upload the application that has the issue to github so we can take a look.

**Comment by vigpatrick** [comment]
Finally i used your example and it work. I guess i forgot the moduleForAcceptance and my test was not lauched properly.

Thank you even though it was a beginner problem.

**Comment by san650** [comment]
@vigpatrick no problem, glad you make it work!

Let us know if you have any question, we're here to help 😃
