### ISSUE TITLE
Documentation Links to default attributes not working

### ISSUE THREAD

**Issue by hidnasio** [san650/ember-cli-page-object#253]
Links in component page for default attributes are not working. I'm getting a github 404 page http://ember-cli-page-object.js.org/docs/v1.6.x/api/actions#clickontext

<img width="1280" alt="links not working" src="https://cloud.githubusercontent.com/assets/2262669/18612801/a8356540-7d3a-11e6-8f8e-8bda1ed1c6e0.png">

**Comment by jeradg** [comment]
Links to properties fixed on the Components and Create pages.

Thanks for reporting this issue @hidnasio!
