### ISSUE TITLE
`triggerable` does not work with native events in integration tests

### ISSUE THREAD

**Issue by leizhao4** [san650/ember-cli-page-object#256]
I have this Page Object

```
PageObject.create({
  blur: triggerable('blur', 'input')
});
```

and try to trigger `blur` event using

```
page.blur();
```

It works fine if I bind my event listener using jQuery. It does not work if I use plain JavaScript `.addEventListener()`.

**Comment by JoshSmith** [comment]
Any ideas on this one?

**Comment by leizhao4** [comment]
@san650 How about switching to [ember-native-dom-helpers](https://github.com/cibernox/ember-native-dom-helpers)?

**Comment by san650** [comment]
You can now use the native-dom-helpers, see https://github.com/san650/ember-cli-page-object/releases/tag/v1.13.0-alpha.1

This is an alpha release, please, report any issue you find.

**Comment by JoshSmith** [comment]
Seeing `v.1.13` is giving me flashbacks, but 💯  regardless.
