### ISSUE TITLE
Documentation 1.6.x is missing collection section

### ISSUE THREAD

**Issue by hidnasio** [san650/ember-cli-page-object#258]
I couldn't find the collection section in 1.6.x documentation website. In 1.5.x is there.

1.6.x screen shot

<img width="689" alt="screen shot 2016-10-01 at 5 57 49 pm" src="https://cloud.githubusercontent.com/assets/2262669/19016986/daaed0b2-8800-11e6-9f31-026cfbf29a38.png">

1.5.x screen shot
<img width="781" alt="screen shot 2016-10-01 at 5 58 01 pm" src="https://cloud.githubusercontent.com/assets/2262669/19016987/dab1670a-8800-11e6-98fc-e2c6ea4cfd39.png">

**Comment by zeppelin** [comment]
@hidnasio @san650 it had been moved to under [properties](http://ember-cli-page-object.js.org/docs/v1.6.x/api/properties#collection), or wasn't this the intention?

However, the description is missing, that's for sure.

**Comment by hidnasio** [comment]
@zeppelin I didn't know that it was under properties, thanks!.

I'll close the issue for now and if the missing of the description is a real issue they can open it again.
