### ISSUE TITLE
Possibility to read the input value from a fillable()

### ISSUE THREAD

**Issue by wecc** [san650/ember-cli-page-object#259]
Being able to fill and then read the value from an input is a scenario I've met several times during testing and it would be really great if there was a way to be able to do this with just a `fillable()` (or possibly named something else).

The built-in `.fillIn()` and `.value` for components are great but limits the fluid-ness of your code. 

Example:

``` js
const page = create({
  name: {
    scope: 'input',
  },
  submit: clickable('button')
});

// calling `fillIn()` on `name` returns the context of `name` so there is no
// access to `.submit()`. Therefor you have to write the code on two lines:
page.visit().name.fillIn('Christoffer'); 
page.submit();

// read the value
page.name.value;
```

An existing alternative would be to define a `fillable()` along with a `value()` like this:

``` js
const page = create({
  name: fillable('input'),
  nameValue: value('input'),
  submit: clickable('button')
});

// calling `name()` returns the root context and you can easily call `.submit()`:
page.visit().name('Christoffer').submit(); 

// read the value
page.nameValue;
```

This works but seems a bit redundant that you have to specify the same selector twice.

Mimicking jQuery's [`.val()`](http://api.jquery.com/val/) it would be nice if a single `fillable()` would allow you to fill the value by passing a parameter and read the value by omitting parameters.

Example:

``` js
const page = create({
  name: fillable('input'),
  submit: clickable('button')
});

// calling `name()` returns the root context and you can easily call `.submit()`:
page.visit().name('Christoffer').submit(); 

// read the value
page.name();
```

Another example proposed by @san650 in the Ember Slack is that ember-cli-page-object automatically defines an accompanying `xyzValue` property for reading the value (just like the second example in this issue, but you wouldn't have to define it manually).

**Comment by backspace** [comment]
What if `value` were one of the [“default attributes” of a component](http://ember-cli-page-object.js.org/docs/v1.8.x/components#default-attributes)? Then you can `fillIn` and check the `value`. The addition of these default attributes is very useful to me and I think this would be even better.

**Comment by backspace** [comment]
hmm never mind, it’s actually already present! 😬

Maybe I’ll make a PR to add it to the documentation…

**Comment by denniss17** [comment]
It would be great if this feature would be added. Something like:
```
address: fillable('input[data-test-input=address]'),
```

When inserting input:
```
component.render(hbs`{{my-component model=user}}`);
component.address('Street 1');

assert.equal(user.address, 'Street 1');
```

When reading:
```
component.render(hbs`{{my-component model=user}}`);
assert.equal(component.address.value(), user.address);
```

So basically `address()` would behave as the result of the `fillable` functions, while `address` would return a component scoped on the same scope. Using this component, the default attributes as specified in [the documentation](http://ember-cli-page-object.js.org/docs/v1.14.x/components#default-attributes) could be used.

**Comment by ro0gr** [comment]
@denniss17 currently `fillIn` and `value` are both available for each page object component, see "Default Attributes" section of the ["Components Doc"](http://ember-cli-page-object.js.org/docs/v1.14.x/components).

This allows us just to declare an address field:
```js
  const form = create({
    address: {
      scope: 'input[data-test-input=address]'
    }
  })
```
and use it in your test in the following form:
```js
  await form.address.fillIn('Street 1');
  assert.equal(form.address.value, 'Street 1');
``` 
Does it work for you?
