### ISSUE TITLE
Link to "Selenium’s wiki page" is broken in docs

### ISSUE THREAD

**Issue by ryanlabouve** [san650/ember-cli-page-object#261]
On the main docs page (http://ember-cli-page-object.js.org/docs/v1.6.x/) the link to "Selenium’s wiki page" is broken.

<img width="603" alt="overview" src="https://cloud.githubusercontent.com/assets/1318878/19936846/0ce0e23c-a0ed-11e6-9dd0-60c640206552.png">

I think it is supposed to point to one of these two:
* https://seleniumhq.github.io/docs/best.html#page_object_models
* https://github.com/SeleniumHQ/selenium/wiki/PageObjects

I'm happy to help with this!

**Comment by san650** [comment]
@ryanlabouve thanks for finding this, if you can fix the links, it would be awesome :)

Please let me know if you have any questions

**Comment by ryanlabouve** [comment]
Cool. I'm fairly certain the link is supposed to be https://seleniumhq.github.io/docs/best.html#page_object_models

I'm trying to figure out where the index page of is located. Maybe it's not in this repo? 

Side note, very cool with what y'all have done with https://github.com/san650/ember-cli-page-object/blob/master/docs.js

**Comment by san650** [comment]
You have to update the `gh-pages` branch which contains the website, the PR need to be against that branch. The file you need to update is https://github.com/san650/ember-cli-page-object/blob/gh-pages/docs/index.html

Also, the link you mention is correct.

Thanks for taking care of this! 😃

**Comment by san650** [comment]
@ryanlabouve sorry, I was wrong about what files do we have to update, the correct files to update are

* https://github.com/san650/ember-cli-page-object/blob/gh-pages/docs/v0.11.x/index.md
...
* https://github.com/san650/ember-cli-page-object/blob/gh-pages/docs/v1.5.x/index.md
* https://github.com/san650/ember-cli-page-object/blob/gh-pages/docs/v1.6.x/index.md

I know it's not the best strategy to have the same page repeated over and over but we're planning on changing that with site redesign in the future. For now we have to update these files.

Thanks again.

**Comment by san650** [comment]
Deployed.

Thanks for contributing!
