### ISSUE TITLE
Add ability to look up items in a collection via properties other than index

### ISSUE THREAD

**Issue by lsthornt** [san650/ember-cli-page-object#288]
Use case:
```js
<ul>
  <li data-test-id='UUID1'>Object 1</li>
  <li data-test-id='UUID2'>Object 2</li>
</ul>

PageObject.create({
  objects: collection({
    scope: 'ul',
    itemScope: 'li'
  })
});

page.objects("[data-test-id='UUID1']");
```
---

This can currently be solved by using nested PageObjects, a la:
```js
PageObject.create({
  objects(uuid) {
    return PageObject.create({
      scope: `[data-test-id='${uuid}']`
    });
  }
});

page.objects('UUID1');
```
However there are some drawbacks to this, including the fact that the outer PageObject's scope will not be inherited.

**Comment by ro0gr** [comment]
https://github.com/san650/ember-cli-page-object/issues/198 related.

**Comment by dadleyy** [comment]
I didn't want to make a completely separate issue for this, but I was wondering if it would be niceto have collections be able to receive a list of indices to return:

```js
const [a,b,c] = page.objects([1,2,3])
vs.
const [a,b,c] = page.objects().toArray();
```

**Comment by dodeja** [comment]
@lsthornt Interesting. How does this work with component integration tests?

**Comment by pzuraq** [comment]
I think this could actually more safely be accomplished by allowing collections to query the page objects of the items in the collections themselves, rather than directly querying the items:

```js
<ul>
  <li data-test-id='UUID1'>Object 1</li>
  <li data-test-id='UUID2'>Object 2</li>
</ul>

PageObject.create({
  objects: collection({
    scope: 'ul',
    itemScope: 'li',

    item: {
      id: attribute('data-test-id')
    }
  })
});

page.objects('id', 'UUID1');
```

This way you aren't breaking encapsulation, the item in the collection gets to define it's own content and values you can search. It could be a completely separate component definition, and you would essentially be searching its public API

**Comment by ro0gr** [comment]
I think we should have a way to describe where an element id can be found. So `id` field sounds like a good candidate for a default collection DSL to me. If we have an `id` we then also need something like `getById`.

```js
const form = create({
  fields: collection({
    scope: 'input',
    id: attribute('name') 
  })
});

const login = form.fields.byId('login')
const password = form.fields.byId('password')
``` 

Hopefully it should be also possible to proxy it like we [do](https://github.com/san650/ember-cli-page-object/blob/e8a2003d39218935a0ae7b2cb03054743b8cce79/addon-test-support/properties/collection/main.js#L96-L105) for positional elements:

```js
const { login, password } = form.fields;
```

**Comment by san650** [comment]
@lsthornt have you tried doing something like this?

```html
<ul>
  <li data-test-id='UUID1'>Object 1</li>
  <li data-test-id='UUID2'>Object 2</li>
</ul>
```

```js
// I'm using the new API for collections here but it should work the same with
// old API
PageObject.create({
  objects: collection('ul li', {
    id: attribute('data-test-id')
  })
});

let li = page.objects().filterBy('id', 'UUID1');
assert.equal(li.text, 'Object 1');

----

// And going a bit further
PageObject.create({
  objects: collection('ul li', {
    id: attribute('data-test-id')
  }),

  objectById(id) {
    return this.objects().filterBy('id', id);
  }
});

assert.equal(page.objectById('UUID2'), 'Object 2');
```

**Comment by ro0gr** [comment]
Assuming the original markup:
```js
<ul>
  <li data-test-id='UUID1'>Object 1</li>
  <li data-test-id='UUID2'>Object 2</li>
</ul>
```
I believe, today we can do it like:
```js
const { objects } = create({
  scope: 'ul',
  objects: collection('li', {
   id: attribute('data-test-id'),
  })
});

objects.findOneBy('id', 'UUID1');
```
