### ISSUE TITLE
Red test after installation: Uncaught SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by rafaltrojanowski** [san650/ember-cli-page-object#29]
Hi, I'm new in acceptance testing with page-objects. I had acceptance test which was green.
I use visit('path').
After PO installation I get global failure: SourceUncaught SyntaxError: Unexpected token =
from /assets/web-app-ember.js:10789

This is error from this function:
`
  function visitable(params = {}) {
    let path = this.path;

    if (path.indexOf(':') !== -1) {
      path = fillInDynamicSegments(path, params);
    }

    this.page.lastPromise = visit(path);

    return this.page;
  }
`

I tried add page object like:

`var page = PageObject.build({
  visit: visitable('/time-sessions'),
});
`
or simply replace visit by visibable.
What I am doing wrong?

**Comment by san650** [comment]
Are you using ES6 object destructuring to get the `visitable` reference?

Try doing something like this:

```js
var page = PageObject.build({
  visit: PageObject.visitable('/time-sessions')
});
```

If that works, you can write the test as follows

```js
var { visitable } = PageObject;

var page = PageObject.build({
  visit: visitable('/time-sessions')
});
```

Also, it would help if you can provide the full test file. Please, let me know how it goes.

**Comment by san650** [comment]
Are you using `ember-cli` with `babeljs` in your project?

**Comment by rafaltrojanowski** [comment]
I don't use babeljs in my CLI project.

This is my test:
`
import Ember from "ember";
import { module, test } from 'qunit';
import FactoryGuy, { make, build } from 'ember-data-factory-guy';
import startApp from '../helpers/start-app';

var App;

module('An Integration test', {
  beforeEach: function() {
    App = startApp();
  },
  afterEach: function() {
    Ember.run(App, App.destroy);
  }
});


test("Page contents", function(assert) {
  assert.expect(1);

  authenticateSession();

  var timeSessionsLength = 3

  var timeSessions = FactoryGuy.makeList('time-session', timeSessionsLength);

  visit('/time-sessions/')

  andThen(function() {
    assert.equal(find('#time-sessions').length, 1, "Page contains list of models");
    assert.equal(find('.session-item').length, timeSessionsLength, "List contains expected number of models");
  });
});
`

Thanks for your instructions. I will check it.

**Comment by rafaltrojanowski** [comment]
I introduced PO to test and still without success.
```
import Ember from "ember";
import { module, test } from 'qunit';
import FactoryGuy, { make, build } from 'ember-data-factory-guy';
import startApp from '../helpers/start-app';
import PO from '../page-object';

var App;

var page = PO.build({
  visit: PO.visitable('/time-sessions')
});

module('An Integration test', {
  beforeEach: function() {
    App = startApp();
  },
  afterEach: function() {
    Ember.run(App, App.destroy);
  }
});

test("Page contents", function(assert) {
  assert.expect(1);

  authenticateSession();

  var timeSessionsLength = 3

  var timeSessions = FactoryGuy.makeList('time-session', timeSessionsLength);

  page.visit();

  andThen(function() {
    assert.equal(find('#time-sessions').length, 1, "Page contains list of models");
    assert.equal(find('.session-item').length, timeSessionsLength, "List contains expected number of models");
  });
});
```

**Comment by rafaltrojanowski** [comment]
I'm not sure if it may be important but I can see:
global failure
    ✘ SyntaxError: Parse error

under 
PhantomJS 1.9┃
    0/1 ✘

in terminal, but it didn't have influence on this particular spec before.

**Comment by san650** [comment]
@rafaltrojanowski `ember-cli-page-object` depends on `ember-cli-babel` versions `^5.0.0`. I believe the error you're getting is from this line

````
function visitable(params = {}) {
...
```

 which needs to be transpiled from ES6 to ES5 before it's loaded by the browsers (or phantomjs).

`ember-cli` has babeljs support by default, what version are you using? Also, do you have some custom publication mechanism in place to build the ember project?

**Comment by rafaltrojanowski** [comment]
@san650 I'm using:
```
DEBUG: Ember                       : 1.12.1
ember.debug.js:4874 DEBUG: Ember Data                  : 1.0.0-beta.19
ember.debug.js:4874 DEBUG: jQuery                      : 1.11.3
ember.debug.js:4874 DEBUG: Ember Simple Auth           : 0.8.0
ember.debug.js:4874 DEBUG: Ember Simple Auth OAuth 2.0 : 0.8.0
ember.debug.js:4874 DEBUG: Ember Simple Auth Testing   : 0.8.0
```
with CLI "0.2.7"

I had ember-cli-babel... only in package.json.bak.
I have complex project with pubnub-ember (poor support for CLI, it also throws errors during specs when I mocked other api requests properly).

I need to check page objects on fresh project, and get more information about ECMAScript.

> have some custom publication mechanism in place to build the ember project?

Hm, rather not!

**Comment by san650** [comment]
Please, do try it on a fresh ember-cli project and let us know what you think about the addon :smiley: 

I'm closing this issue now because it doesn't seems to be a problem with the ember-cli-page-object addon.
