### ISSUE TITLE
Add `none` helper

### ISSUE THREAD

**Issue by magistrula** [san650/ember-cli-page-object#299]
Given the following test...
```javascript
it('can clear the Roster', function() {
  RosterPageObject.clearRoster();

  // expect Roster to be in its initial state
  expect(RosterPageObject.rosterNames().count).to.equal(0);
  expect(RosterPageObject.nameInputValue).to.equal('');
  expect(RosterPageObject.isClearButtonVisible).to.be.false;
});
```
It may be helpful for the PageObject to define what it means for the Roster to be "empty" so that the tests don't have to check each individual criterion, and so that these criteria do not need to be repeated every time we need to check whether the roster is empty. A `none` helper would be useful in this case:
```javascript
const RosterPageObject = create({
  rosterNames: collection({
    itemScope: '.roster-name'
  }),
  nameInputValue: value('.name-input'),
  isClearButtonVisible: isVisible('.clear-button'),

  isRosterBlank: none('rosterNames', 'nameInputValue', 'isClearButtonVisible')
});
```
This would allow the test above to be rewritten as follows:
```javascript
it('can clear the Roster', function() {
  RosterPageObject.clearRoster();

  expect(RosterPageObject.isRosterBlank).to.be.true;
});
```

**Comment by ro0gr** [comment]
Closing, since it can be achieved with getters. see https://github.com/san650/ember-cli-page-object/issues/300#issuecomment-447298318
