### ISSUE TITLE
Add `every` helper

### ISSUE THREAD

**Issue by magistrula** [san650/ember-cli-page-object#300]
Given the following test...
```javascript
it('disables all parts of the form while saving ', function() {
  PageObject.saveForm();

  expect(PageObject.isOptionsDropdownDisabled).to.be.true;
  expect(PageObject.isInputDisabled).to.be.true;
  expect(PageObject.isSubmitButtonDisabled).to.be.true;
});
```
It may be helpful for the PageObject to define what it means for all parts of the form to be disabled so that the tests don't have to check each individual criterion, and so that these criteria do not need to be repeated every time we need to check whether the UI is disabled. An `every` helper would be useful in this case:
```javascript
const PageObject = create({
  isOptionsDropdownDisabled: hasClass('is-disabled', '.dropdown'),
  isInputDisabled: is(':disabled', 'input'),
  isSubmitButtonDisabled: is(':disabled', 'button'),

  isFormDisabled: every('isOptionsDropdownDisabled', 'isInputDisabled', 'isSubmitButtonDisabled')
});
```
This would allow the test above to be rewritten as follows:
```javascript
it('disables all parts of the form while saving ', function() {
  PageObject.saveForm();

  expect(PageObject.isFormDisabled).to.be.true;
});
```

**Comment by mistahenry** [comment]
`getter` already solves this and IMO in a better way. 

```javascript
const page = create({
  isInputDisabled: is(':disabled', 'input'),
  isSubmitButtonDisabled: is(':disabled', 'button'),
  allDisabled: getter(function(){
    return this.isInputDisabled && this.isSubmitButtonDisabled
  })
});
```

I wouldn't advocate for an approach that matches strings to the page object keys. Besides brittleness, you wouldn't be able to use most IDEs / editors ability to rename

**Comment by ro0gr** [comment]
Agree. In addition to IDEs/editors argument, it's close to impossible to cover string based paths by types.

**Comment by ro0gr** [comment]
ok, let's close it. Thanks @mistahenry
