### ISSUE TITLE
new Ember.Error in better-error not logging the message in the console

### ISSUE THREAD

**Issue by Leooo** [san650/ember-cli-page-object#304]
using Ember 2.10.2, on Chrome

https://github.com/san650/ember-cli-page-object/blob/master/addon/-private/better-errors.js#L22

the message is not logged in the console

add a `console.error` call before the error to make sure it is logged?

**Comment by san650** [comment]
What's strange is that errors were being logged before, so something changed (in Ember?) that makes this error not to be logged anymore.

I remember that was a change in how backburner reported exceptions when env was testing, see https://github.com/emberjs/ember.js/pull/14898. Maybe is related to that.

Having the exception in the console is super useful so I think we should log it ourself if it's not printed by Ember.
