### ISSUE TITLE
The option '--page-object' is not registered

### ISSUE THREAD

**Issue by stephanebruckert** [san650/ember-cli-page-object#319]
$ ember install ember-cli-page-object

Doing so as mentioned in the README:

    ✗ ember g component my-component --page-object

But getting

> The option '--page-object' is not registered with the generate command. Run `ember generate --help` for a list of supported options.

Why?

**Comment by san650** [comment]
@stephanebruckert we're removing this blueprint because it was difficult to maintain. This blueprint is a good candidate to be its own ember addon.

If anyone wants to create a new ember addon with it, here's the code: 
 https://github.com/san650/ember-cli-page-object/pull/274/files
