### ISSUE TITLE
Addon not raising the correct error when not initialising the page object.

### ISSUE THREAD

**Issue by ghost** [san650/ember-cli-page-object#322]
Page object:
```
import {
    create,
    text
} from 'ember-cli-page-object';

export default create({
  value: text('.button-regular')
});
```

Test:
```
import {
  moduleForComponent,
  test
} from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';

import pageObject from 'dummy/tests/pages/components/teacher/ui/buttons/button-regular';

moduleForComponent('teacher/ui/buttons/button-regular', 'Integration | Component | teacher/ui/buttons/button-regular', {
  integration: true
});

test('The button-regular (teacher) renders', function(assert) {
  this.render(hbs '
	  {{teacher/ui/buttons/button-regular
		  givenSize="SMALL"
		  givenColor="PRIMARY"
		  textValue="Johan"
	  }}');

  assert.equal(pageObject.value, 'Johan', 'Button has the correct value.');
});
```

In this case, i forgot to initialise the Page object inside the `moduleForComponent`. This should have been.

```
moduleForComponent('teacher/ui/buttons/button-regular', 'Integration | Component | teacher/ui/buttons/button-regular', {
  integration: true,

  beforeEach() {
    pageObject.setContext(this);
  },

  afterEach() {
    pageObject.removeContext();
  }
});
```

The error thrown by the test, leaded me the wrong way. 

> Assertion Failed: ".button-regular" matched more than one element. If this is not an error use { multiple: true }

The above thrown error, lead me searching inside the Page Object for the solution. Instead, i had to initialise the Page Object inside the test.

Suggestion:
Better error message for this, and might also some other, errors. :)

**Comment by sukima** [comment]
Confused, Does this already take place: https://github.com/san650/ember-cli-page-object/blob/master/addon/-private/context.js#L20-L25

Why didn't the above code that is missing the context not throw this error?!

**Comment by sukima** [comment]
@Ronald-Gynzy you used `this.render(…)` **not** `pageObject.render(…)` and there for that is why things went way wrong.

@san650 This is **not** a bug because [the code *does* work as intended](https://github.com/san650/ember-cli-page-object/blob/master/addon/-private/context.js#L20-L25). The problem is that the page object was never used to render the component.

**Comment by san650** [comment]
@sukima Thanks for bringing this up. Using the page object's render function is optional. You can use test's `this.render` function.

**Comment by san650** [comment]
Expanding my above answer: We added `component.render` function to allow people to chain calls as we do with other parts of the page-object. But that doesn't mean that you _have_ to use it, you can still use the regular `this.render` function.

I think we could add a better error message to help users fix the problem.

**Comment by Ronald-Gynzy** [comment]
@sukima Never knew about the opportunity to use `pageObject.render(...)`. Thanks for mentioning.

**Comment by ro0gr** [comment]
This should not be an issue anymore. In 1.16.0 you don't need `setContext` if you are on the latest of "@ember/test-helper".

More details - http://ember-cli-page-object.js.org/docs/v1.16.x/deprecations#set-context
