### ISSUE TITLE
How to write a page object that clicks specific index?

### ISSUE THREAD

**Issue by bdiz** [san650/ember-cli-page-object#326]
I'm trying to define a page object method that will allow me to click a specific element of the selection.

```
{
  visit: visitable('/'),
  clickSpecificElement(index) {
    return clickable('.class-name', {at: index});
  }
}
```
And then later in my test I could do: 

`page.clickSpecificElement(3);`

Is this not the way? Presumably not, since it's not working. :)

Thanks. Love the tool by the way.

**Comment by san650** [comment]
You have to use a collection for that

```js
const page = create({
  visit: visitable('/'),
  elements: collection({
    itemScope: '.class-name'
  })
});
```

and then you can use it like this

```js
page.elements(3).click();
```

You can get more info about collections here http://ember-cli-page-object.js.org/docs/v1.8.x/api/collection
