### ISSUE TITLE
Selector scope concatenation does not work with comma selector

### ISSUE THREAD

**Issue by ming-codes** [san650/ember-cli-page-object#335]
```
create({
  scope: '.level-1', 

  nested: {
    scope: '.one, .two'
  }
})
```

Expected: `.level-1 .one, .level-1 .two`

Actual: `.level-1 .one, .two`

**Comment by san650** [comment]
Thanks for opening the issue (and the PR).

We never intended to support multiple selectors (group). We feel it makes the page object harder to reason about and it can be easily avoided by using `data-test-*` selectors or a custom css selector.

Adding support for this would also make the selector logic more complex which is something we're trying to avoid.
