### ISSUE TITLE
Appears to break when included in nested addons

### ISSUE THREAD

**Issue by pzuraq** [san650/ember-cli-page-object#337]
It appears that the inclusion strategy in `treeFor` doesn't work when included in nested addons. I haven't been able to figure out exactly why, but I can't seem to get the correct context from anywhere.

We could switch to using a similar strategy to [ember-native-dom-helpers](https://github.com/cibernox/ember-native-dom-helpers/blob/master/index.js#L7) to provide the same external API, but not determine whether or not to include things ourselves. Let `ember-cli` decide based on public hooks.

**Comment by ro0gr** [comment]
Do I understand correctly that you need to be able to access `ember-cli-page-object` without an explicit dependency on it in a `package.json`?
