### ISSUE TITLE
v1 deprecations

### ISSUE THREAD

**Issue by ro0gr** [san650/ember-cli-page-object#344]
We need a place to plan deprecations:

- [multiple selectors (group)](https://github.com/san650/ember-cli-page-object/issues/335#issuecomment-344248732)

**Comment by ro0gr** [comment]
I would like to consider `page.render()` to be deprecated.

Are there any benefits of `page.render()` vs `htmlbars-inline-precompile`?

**Comment by san650** [comment]
Closed in favor of #359
