### ISSUE TITLE
Parsing variables in selectors

### ISSUE THREAD

**Issue by ab9-er** [san650/ember-cli-page-object#358]
I am trying to build a page object but the selector that I am using in the clickable function has a variable like,

```
export default PageObject.create({
    ddSelect: clickable(`[test-selector="${testValue}"]`)
})
```

The problem is I cannot reference the variable `${testValue}`. Do you have any ideas how can I go about it ?

**Comment by ro0gr** [comment]
You can't access it cause you haven't `testValue` variable defined. I'm not sure what you're trying to achieve but to make it not fail you have to define the variable:
```
const testValue = 'test-value';

export default PageObject.create({
    ddSelect: clickable(`[test-selector="${testValue}"]`)
})
```
