### ISSUE TITLE
Implement Namespaces

### ISSUE THREAD

**Issue by juanazam** [san650/ember-cli-page-object#36]
Given the following HTML

```html
<div class="princing-modal">
  <div class="irrelavant-for-testing-info">
  </div>
  <div class="important-stuff">
    <span class="cost">30$</span>
    <span class="billing-date">30/12/2015</span>
  </div>
</div>
```
In order to test this comfortably with the current implementation I would build a PO component which looks like:

```js
{
  scope: '.pricing-modal',
  importantSuff: {
     scope: '.important-stuff' 
     cost: text('.cost'),
     billingDate: text('.billing-date')
  }
}
```
So I don't have to repeat the '.important-stuff selector' for both texts I want to check.

In order to access those values, I would have to write `page.pricingModal().importantStuff().cost()` to get the actual cost text. It would be great that `page.pricingModal().cost()` returned the proper selector, without having to repeat the `.important-stuff` selector on each property.

Here come namespaces:

```js
{
  scope: '.pricing-modal',
  importantSuff: namespace({
     scope: '.important-stuff' 
     cost: text('.cost'),
     billingDate: text('.billing-date')
  })
}

Would generate the proper selectors without having to repeat selector and generating extra calls in tests.

**Comment by juanazam** [comment]
@san650 thoughts?

**Comment by san650** [comment]
Isnt' this the same as ...?

```js
{
  scope: '.pricing-modal .important-stuff',
  cost: text('.cost'),
  billingDate: text('.billing-date')
}
```

**Comment by juanazam** [comment]
Wouldn't work if I had other information I want to test outside the "irrelevant" section

**Comment by san650** [comment]
So...

```js
{
  scope: '.pricing-modal',
  otherProperty: text('...'),
  importantSuff: scoped('.important-stuff', {
     cost: text('.cost'),
     billingDate: text('.billing-date')
  })
}
```
would be transformed into something like...

```js
{
  scope: '.pricing-modal',
  otherProperty: text('...'),
  cost: text('.cost', { scope: '.pricing-modal .important-stuff' }),
  billingDate: text('.billing-date', { scope: '.pricing-modal .important-stuff' })
}
```

Right?

I'm not totally convinced, my main concerns are:
* You're telling people that it's ok to group attributes by their css class rather than grouping them by their semantic (the whole point of the pattern)
* Is not clear what happens with the `importantSuff` key. That key is just stripped out.

Saying that, I'm not against implementing something like this and see how it goes. Also, I prefer the name `scoped` rather than `namespace`, it tells more precisely what it really does. What do you think?

**Comment by juanazam** [comment]
The translation is correct, as you can see, the first option is clearer than the second one.

Regarding you concerns:

* I'm telling people there is a way of scoping some part of the page easily without having to create a function afterwards to do so or having to write code that is less understandable. Sometimes web apps have sections of pages which are useful for users but don't want to be tested and as a developer we want to keep that separated easily.
* The `importantStuff` key dissapers, and should not be used to navigate on the object `page.modal().cost()` would look where it should.

**Comment by san650** [comment]
Well, I think the user has several options already to make it more readable

Using variables

```js
let importantStuff = { scope: '.pricing-modal .important-stuff' };

page = build({
  scope: '.pricing-modal',

  otherProperty: text('...'),

  cost: text('.cost', importantStuff),
  billingDate: text('.billing-date', importantStuff)
});
```

Scoping what changes:

```js
page = build({
  scope: '.pricing-modal .important-stuff',

  otherProperty: text('...', { scope: '.pricing-modal' }),

  cost: text('.cost'),
  billingDate: text('.billing-date')
});
```

And the default it's no so bad either

```js
page = build({
  scope: '.pricing-modal',

  otherProperty: text('...'),

  cost: text('.important-stuff .cost'),
  billingDate: text('.important-stuff .billing-date')
});
```

I mean, maybe it's useful on big page objects, but I think people already have alternatives to make it more readable.

But, as I said, let's go for it and see how it goes.

**Comment by juanazam** [comment]
:+1:

Still think any of them is as clear as the proposed solution, I guess we can implement it and see how it goes, if looks good, we can merge it in.
