### ISSUE TITLE
visitable API changed in 1.13: slashes are now encoded

### ISSUE THREAD

**Issue by backspace** [san650/ember-cli-page-object#376]
Hey, I’m finally digging into a breaking change I saw the effects of in [1.13](https://github.com/travis-ci/travis-web/pull/1456), only because Greenkeeper then made a PR for 1.14 haha 😳 

At the time, I was too busy to look into the problem, but I now understand: the handling of a URL segment with a `/` has changed. In `travis-web`, we use a repository “slug” as an entire entity sometimes, with the owner and repository combined, like this: `travis-ci/travis-web`. So in the page object for a build page, we [have](https://github.com/travis-ci/travis-web/blob/d567b169caade876bf7ec24f7511b78eed7abed9/tests/pages/build.js#L33):

```
  visit: visitable(':slug/builds/:build_id'),
```

It used to be that we could use it [this way](https://github.com/travis-ci/travis-web/blob/4d89a80318fa1a4f1ba2c31a39b818563eff5e9f/tests/acceptance/builds/cancel-test.js#L30):

```
    .visit({ slug: 'travis-ci/travis-web', build_id: build.id })
```

But now, as you can see in a [test log](https://travis-ci.org/travis-ci/travis-web/builds/337789418#L561-L562) (from a different test that asserts against `currentURL()`), that doesn’t work:

```
     expected: 'adal/difference-engine'
       actual: 'adal%2Fdifference-engine'
```

Maybe this is technically a violation of semantic versioning?

I can change our page objects to split `slug` into `owner` and `repo` to address these test failures, but I thought you might like to know. Thanks for all your work on this!

**Comment by san650** [comment]
@backspace this is definitely a violation of semantic versioning! We'll address the issue. I know there's people expecting this new behavior, what we can do is have a config flag to turn this new behavior on.

I'll try to address this issue this week, sorry for the inconvenience.

**Comment by backspace** [comment]
It’s not a huge deal, just something I noticed while updating from 1.12 to 1.14. Thanks for looking into it!
