### ISSUE TITLE
visit is not defined

### ISSUE THREAD

**Issue by wayne-o** [san650/ember-cli-page-object#380]
I have just created a new project, added some code from the quickstart and for some reason I keep getting "visit is not defined"

You can see the project here: https://github.com/wayne-o/brownbag-todo

**Comment by wayne-o** [comment]
This happens at line 27 of this file:
```define('ember-cli-page-object/-private/execution_context/acceptance', ['exports', 'ember-cli-page-object/-private/helpers', 'ember-cli-page-object/-private/execution_context/helpers', 'ember-cli-page-object/-private/better-errors'], function (exports, _helpers, _helpers2, _betterErrors) {
  'use strict';```

**Comment by wayne-o** [comment]
or in this repo, here: https://github.com/san650/ember-cli-page-object/blob/master/addon/-private/execution_context/acceptance.js#L34

**Comment by san650** [comment]
We don't have support for the new test API in master yet, we do have a PR for adding that #357.

We plan to merge this one soon, sorry the inconvenience

**Comment by yohanmishkin** [comment]
Is this issue still a problem with PR #357 having been merged?

**Comment by yohanmishkin** [comment]
Ah, I see it's still in pre-release (v1.15.0-beta.1).

**Comment by san650** [comment]
@yohanmishkin you're right, this is fixed in master.

**Comment by cwhittl** [comment]
I'm seeing this in the latest version of Ember and latest of this library.  Could it be a similar issue?
