### ISSUE TITLE
Unclear findElement/findElementWithAssert import path

### ISSUE THREAD

**Issue by ro0gr** [san650/ember-cli-page-object#388]
`findElement` and `findElementWithAssert` are currently exported from [index.js](https://github.com/san650/ember-cli-page-object/blob/17dbadd4e23310a9948a0767bff6ba395fc9c9ca/addon/index.js#L24-L25) and and [extend.js](https://github.com/san650/ember-cli-page-object/blob/17dbadd4e23310a9948a0767bff6ba395fc9c9ca/addon/extend.js#L1-L2).
Different import paths are also suggested in the docs for these helpers.

I feel importing it from `ember-cli-page-object/extend` is a recommended way but want to confirm first. 
If so we should likely deprecate the other import path and fix the docs.

**Comment by san650** [comment]
The idea is to use the `ember-cli-page-object/extend` path. Let's deprecate the other export path!.

**Comment by ro0gr** [comment]
I [think](https://github.com/san650/ember-cli-page-object/issues/359#issuecomment-447503955) `findElement`/`findElementWithAssert` should be deprecated and removed from v2 in favour of new native DOM finder alternative. 

Need a ticket for that new method(s) design.

**Comment by ro0gr** [comment]
finally https://github.com/san650/ember-cli-page-object/issues/463
