### ISSUE TITLE
New collection API, trying to upgrade and stuck on a scope question...

### ISSUE THREAD

**Issue by josh803316** [san650/ember-cli-page-object#393]
For some reason, when I upgrade and use the new collection API... when I reference #filters__selected  in the example below I am not filtering by the filters__selected scope and find all the buttons instead of just the buttons inside the filters__selected div.

```html
<div id="filters">
  <button type="button"> Outer Button </button>
  <div id="filters__selected">
   <button type="button"> Test Button </button>
  </div>
</div>
```

old:

```javascript
const filters = {
  scope: '#filters',
  
  selected: collection({
    scope: '#filters__selected',

    itemScope: 'button',

    item: {
      label: text()
    }
  }),
```

new:
```javascript
const filters = {
  scope: '#filters',

  selected: collection('button', {
    scope: '#filters__selected',
    label: text()
  }),
```

`filters.selected` ends up having more button items than I would expect given my previous test... am I using the new API incorrectly?

The only examples I could find were in this deprecation warning [gist](https://gist.github.com/san650/17174e4b7b1fd80b049a47eb456a7cdc#file-old-collection-api-js)

**Comment by san650** [comment]
Hi @josh803316, can you try this?

```js
const filters = {
  scope: '#filters',

  selected: collection('#filters__selected button', {
    label: text()
  }),
```

The attribute `scope` inside collections doesn't work anymore like it used to. Everything you define in the second argument of `collection` is used in the item context.

Let me know if this fixes the issue and if you have any other question.

**Comment by josh803316** [comment]
Yes, looks like that works @san650 - Thanks for the guidance

**Comment by josh803316** [comment]
Follow up question, but similar in nature... it seems the following worked in the legacy collection model but not the new one:

```javascript
export default create({
...
includeBucket: collection('.bucket-container:eq(0) .location-list [data-table-block=fixed] [data-row-index].ui-tr', {
    scope: '.bucket-container:eq(0) .location-list',
    area: text('.ui-td.title', { at: 0 }),
    addToInclude: triggerable('click', '.include-icon-wrapper button'),
    addToExclude: triggerable('click', '.exclude-icon-wrapper button'),
    noData: text('.no-data', { at: 0 }),
    clearAll: triggerable('click', '.clear-all')
  }),```

when I reference pageObject.includeBucket.clearAll() - I get the error that clearAll is not a function... how should I be doing something that acts on the entire collection?

**Comment by san650** [comment]
@josh803316 one of the changes we did to the collection API is that we don't have the concept of collection level functions, e.g `pageObject.includeBucket.clearAll()`

I would rewrite your example as:

```js
export default create({
...

  includeBucket: collection('.bucket-container:eq(0) .location-list [data-table-block=fixed] [data-row-index].ui-tr', {
    area: text('.ui-td.title', { at: 0 }),
    addToInclude: triggerable('click', '.include-icon-wrapper button'),
    addToExclude: triggerable('click', '.exclude-icon-wrapper button'),
    noData: text('.no-data', { at: 0 }),
  }),

  clearAllIncludedBuckets: clickable('.bucket-container:eq(0) .location-list .clear-all')
```

As you can see, I removed the `scope` attribute from inside the collection and moved the `clearAll` function to outside also.

Please, let me know if this works for you.

---

Apart from that, looking at the snippet I have two questions:
1. Why do you use `triggerable` to trigger the `click` event? We have the `clickable` helper for this. Maybe I'm missing something from the example.
2. This selector `.bucket-container:eq(0) .location-list [data-table-block=fixed] [data-row-index].ui-tr` looks scary 😄 and seems to be very fragile. Have you tried using `data-test` attributes for identify elements in the DOM instead? Check [ember-test-selectors](https://github.com/simplabs/ember-test-selectors)

For (2) the idea is that in your HTML you put `data-test` attributes so you can get the DOM elements in your tests "easily".

```html
<table>
  <tr data-test-bucket>
    ... the rest of the row ...
   </tr>
</table>
```

Then in your test you can just do

```js
includeBucket: collection('[data-test-bucket]', { ... })
```

Sorry if I've deviated too far from your original question 😅

**Comment by josh803316** [comment]
@san650 Thanks so much for the detailed explanation! I am doing the upgrade but did not write the original code or tests so I'm not sure why they weren't using clickable, but I'm going to change the tests to appropriately use it. I also agree about those selectors although it seems they were using the outer and inner scope before for all their collection related stuff... I'll see if I can switch to the ember-test-selector paradigm as that seems valuable and well designed. There are almost 1000 acceptance tests and most of them use ember-cli-page-object (and many collections) so I'm having to do quite a lot of re-writing, thanks again for your help, soo soo appreciated!
