### ISSUE TITLE
Beta version marked as latest in npm

### ISSUE THREAD

**Issue by danwenzel** [san650/ember-cli-page-object#413]
Version 1.15.0-beta.3 is marked as the "latest" version in npm.  This should not be, as "latest" should be the last stable version, not a beta version.

https://www.npmjs.com/package/ember-cli-page-object#versions

**Comment by san650** [comment]
We could release the final version v1.15.0 or republish v1.14.x as latest

**Comment by san650** [comment]
Playing a bit with [`npm-dist-tag`](https://docs.npmjs.com/cli/dist-tag) did the trick!

<img width="672" alt="screen shot 2018-06-13 at 7 57 02 pm" src="https://user-images.githubusercontent.com/1234607/41382777-0b24c14e-6f44-11e8-93a8-dda2cd514468.png">

Thanks @danwenzel for pointing this out!

**Comment by danwenzel** [comment]
🎉  Thanks!

**Comment by san650** [comment]
Just for future reference, I've updated the wiki on how to publish beta versions

https://github.com/san650/ember-cli-page-object/wiki/How-to-release-a-new-version
