### ISSUE TITLE
Ember.logger is deprected

### ISSUE THREAD

**Issue by Dhaulagiri** [san650/ember-cli-page-object#422]
Forthcoming ember releases will ship with a [deprecation](https://github.com/emberjs/rfcs/pull/297) of `Ember.logger`, so [this](https://github.com/san650/ember-cli-page-object/blob/9eb38bd93e8b034fb6ed62787367425420d3a1cb/addon-test-support/-private/better-errors.js#L5) will need to be adjusted to account for the deprecation.

**Comment by mistahenry** [comment]
Can be closed now that [425](https://github.com/san650/ember-cli-page-object/pull/425) has merged
