### ISSUE TITLE
Clickable or clickOn with async?

### ISSUE THREAD

**Issue by Yathi** [san650/ember-cli-page-object#429]
The docs don't seem to be using async/await. I tried adding `await` in front of my clickable call and it doesn't seem to be working. 

So I looked into the docs and I see that one of the PRs uses `await page.clickOn()`. But how does `clickOn()` work? I tried passing in a class into it, and that did not seem to work. Any help is appreciated. Thank you! :)

**Comment by san650** [comment]
async/await should work for all actions (including `clickable`).

```js
var page = create({
  clickButton: clickable(".btn")
});

await page.clickButton()
```
☝️ this should work, if it doesn't, please open a bug with an page object example and the version of the addon that you're using.

There's another helper named `clickOnText` that works this way:

```js
var page = create({
  clickButton: clickOnText('.btn')
});

await page.clickButton('save'); // where "save" is the `innerText` of the button
```

You can see the documentation here: http://ember-cli-page-object.js.org/docs/v1.14.x/api/click-on-text

Apart from that, remember that all "objects" in a page object expose some handy functions (pre-generated for you) so you don't have to define them all the time, e.g. `clickOn`

```js
var page = create({ /*empty definition */});

await page.clickOn("save"); // searches for an element with the text "save" and clicks it
```

You can see the list of these pre-generated helpers here http://ember-cli-page-object.js.org/docs/v1.14.x/components#default-attributes

Please, let me know if this answers your questions and if you're able to make it work 😃 

Also, I wrote a post a long time ago about using async/await with ember-cli-page-object you can checkout https://wyeworks.com/blog/2016/6/13/using-async-and-await-with-ember-cli-page-object

**Comment by san650** [comment]
Feel free to open the issue again if my previous answer is not enough.
