### ISSUE TITLE
"visit" with dynamic segments

### ISSUE THREAD

**Issue by jackmatt2** [san650/ember-cli-page-object#44]
I do I handle dynamic segment in a route

In a normal test I would do
```javascript
    visit(`/booking/${booking.id}/account`);
```

This is what I want
```javascript
export default PageObject.build({
  visit: visitable('/booking/:id'),
});
```

And then in my test 
```javascript
pageObject.visit({id: booking.id})
```

Is this sort of thing supported or is there a workaround for this?

**Comment by jackmatt2** [comment]
Haha, just saw it in the docs now.

**Comment by juanazam** [comment]
:smile:
