### ISSUE TITLE
Deprecate "is" helper

### ISSUE THREAD

**Issue by ro0gr** [san650/ember-cli-page-object#442]
It exposes jQuery to consumer, which should be avoided

**Comment by evanb2** [comment]
Looks like there are quite a few methods that raise the jQuery deprecation in addition to `is()`

<img width="681" alt="Screen Shot 2019-11-05 at 2 51 02 PM" src="https://user-images.githubusercontent.com/11276439/68249874-ea483700-ffdc-11e9-980f-60f9ee6680a7.png">

**Comment by ro0gr** [comment]
@evanb2 looks like you use new testing APIs `setupRenderingTest` + `setContext` in your test. Can you confirm it please? If such, I'd bet you just have to remove `setContext`.

`setContext(this)` or `create({ context: this, ... })` currently enforces legacy `moduleForComponent` test helpers, which is likely a reason of deprecations you are seing. If you use `setup**Test`, most likely you don't need that legacy behavior. 

We are currently actively working on deprecating this confusing behavior https://github.com/san650/ember-cli-page-object/pull/448.

**Comment by evanb2** [comment]
@ro0gr Oh snap! Yeah removing `setContext(this)` fixed it.

**Comment by cah-briangantzler** [comment]
This made it into 1.6x and Im now seeing the deprecations, however I find no suggestion on what to do instead. Any guidance?

**Comment by ro0gr** [comment]
@cah-briangantzler yes, we miss a relevant deprecation section in the deprecation docs page. That's the reason this issue is not closed yet. Thanks for raising it and sorry for inconvinience!

Using of `is` encourages users+ec-page-object to depend on JQuery-specific pseudo selectors, and, I believe, in a long run we aim to avoid JQuery selectors in user land by default. A proposed strategy would be to implement custom getter which does one explicit thing, so instead of:

```js
  isDisabled: is('disabled')
```

the user should implement their own attribute for `disabled`, like:

```js
import { findElementWithAssert } from 'ember-cli-page-object/extend';

export default function isDisabled(selector, options = {}) {
  return {
    isDescriptor: true,

    get() {
      return findElementWithAssert(this, selector, options)[0].disabled;
    }
  };
}

```

and then use it like:

```js
  isDisabled: isDisabled()
```

does it work for you? Maybe you can share your use case, so we can understand better how the `is` is currently used and maybe incorporate it to the deprecation guide?

**Comment by cah-briangantzler** [comment]
We currently use is for disabled and checked. 

From reading the above code I understand, but rather than everyone recreating this code, would be nice if it was supplied as part of the addon.

Was talking with another team here and this is what they did

```isDisabled: attribute("disabled", ""),``` 

If this is correct, it may be better in the long run .

for the checked they did this

```isChecked: property('checked', 'input')```

I had previously used `is` in both cases.

**Comment by ro0gr** [comment]
Nice, thanks for examples, I think these are good candidates for the docs!

`isChecked` example looks good to me. 

And I'm afraid with `isDisabled` calculated via `attribute` you may encounter some issues. AFAIK HTML attributes are static, so once element being rendered, its `disabled` attribute would never change. 

I think for both cases(`checked` and `disabled`), if it's supposed to be ran against HTML Input element, it should be safe to use `property`, like:

```
isDisabled: property('disabled')
```

at least I can find such a snippet for `isDisabled` in one of my projects 😄

**Comment by ro0gr** [comment]
maybe for known cases, like 2 mentioned above, it would be easy to write a codemod to ease migration
