### ISSUE TITLE
Non-present, irrelevant PO element "not found" when inspecting/logging in test file

### ISSUE THREAD

**Issue by shamrt** [san650/ember-cli-page-object#452]
So. This is a bizarre issue, I think.

I'm using a combination of `ember-cli-page-object` and `ember-test-selectors` to perform tests in a large application.

## Problem

1. Create a page object file that has elements that are not always (or never) present on the DOM.
2. Use page object pattern in (acceptance) test file.
3. Attempt to inspect the imported page object in the test file (via `console.log`):
    
    ```js
    console.log("page :", page);
    ```

Following that sequence, an exception is thrown, indicating that the non-present or non-existent:

```sh
Error: Element not found.
```

As far as I understand things, if the element in question is not referenced anywhere, the page object property should not be evaluated; in other words, all page object props should be lazily evaluated and no error should occur.

NOTE: In order to be sure, I removed the `ember-test-selectors` dependency and it is not the culprit here. It also doesn't appear to matter whether the element selector is `[data-test-does-not-exist]` or `.non-existent`.

## Example replication

I've set up a [repo with a trivial extension of the Ember Super Rentals app](https://github.com/shamrt/ember-super-rentals/tree/po-console-bug), which replicates the issue. The relevant files are:

- [`tests/pages/rental.js`](https://github.com/shamrt/ember-super-rentals/blob/po-console-bug/tests/pages/rental.js)
- [`tests/acceptance/list-rentals-test.js`](https://github.com/shamrt/ember-super-rentals/blob/po-console-bug/tests/acceptance/list-rentals-test.js)
- [`app/templates/rentals/show.hbs`](https://github.com/shamrt/ember-super-rentals/blob/po-console-bug/app/templates/rentals/show.hbs)

The following is CLI output from running that branch's Ember test suite:

```sh
± |po-console-bug ✓| → ember t -r dot
Environment: test
cleaning up...
Built project successfully. Stored in "[temporary-file]".

  ........F....................................................
  ...............

  76 tests complete (3322 ms)

  9) [Chrome 73.0] Acceptance | list rentals: should show details for a selected rental
     Promise rejected during "should show details for a selected rental": Element not found.

PageObject: 'page.doesNotExist'
  Selector: '[data-test-does-not-exist]'

     Error: Element not found.

     PageObject: 'page.doesNotExist'
       Selector: '[data-test-does-not-exist]'
         at throwBetterError (http://localhost:7357/assets/test-support.js:11817:11)
         at ExecutionContext.findWithAssert (http://localhost:7357/assets/test-support.js:12800:44)
         at findElementWithAssert (http://localhost:7357/assets/test-support.js:13436:72)
         at Object.get (http://localhost:7357/assets/test-support.js:16017:58)
         at Object.doesNotExist (http://localhost:7357/assets/test-support.js:2603:31)
         at derez (http://localhost:7357/testem.js:111:35)
         at derez (http://localhost:7357/testem.js:102:19)
         at derez (http://localhost:7357/testem.js:111:24)
         at decycle (http://localhost:7357/testem.js:119:4)
         at Object.serializeMessage (http://localhost:7357/testem.js:951:17)

Testem finished with non-zero exit code. Tests failed.
```

**Comment by ro0gr** [comment]
Can't reproduce with super-rentals reproduction you've provided. Do you still have the issue?
