### ISSUE TITLE
Introduce DOM element finders

### ISSUE THREAD

**Issue by ro0gr** [san650/ember-cli-page-object#463]
## Summary

Introduce `findOne` and `findMany` for searching plain DOM elements by JQuery selector.

Deprecate existing `findElement`/`findElementWithAssert` in v1.

## Motivation

Today we have the following methods to find in the DOM:

```ts
function findElement(pageObject: PageObjectNode, scope?: string, options?: FindOptions): JQuery;

function findElementWithAssert(pageObject: PageObjectNode, scope?: string, options?: FindOptions): JQuery;
```

both of them return `jQuery` element collections which should be eliminated to reduce leakage of `jQuery` to the end user.

Also though they return collection, a collection contains a single Element by default. You can disable this behavior by passing an additional `multiple` option set to `true`. But here it starts conflicting with a finder name, cause with `multiple` we look for many element**s** with a  `findElement`.

## Detailed design

```ts
/**
 * Looks for a single element by JQuery selector
 *
 * @throws If no elements found
 * @throws If more than one element found
 */
function findOne(pageObject: PageObjectNode, scope?: string, options?: FindOptions): Element;

/**
 * Looks for elements matching by JQuery selector
 */
function findMany(pageObject: PageObjectNode, scope?: string, options?: FindOptions): Array<Element>;
```

Neither of these methods need a `multiple` flag, cause it's pretty straighforward which method to use when you need elements list. Also, If you just need to check if the element exists without throwing, you can check elements count returned by `findMany`. 

And probably the most important, we don't return a `JQuery` collection anymore. Note that we still allow jquery-like selectors, this is necessary to make `collection` work. Anyway, with the new finders we should be able to switch to a different search implementations compatible with jquery-like selectors.

## How we teach this

 - update docs
 - add a codemod to ease migration - [ember-page-object-codemod](https://www.npmjs.com/package/ember-page-object-codemod)

## Drawbacks

 It's a breaking change. However if we ever want to get rid of JQuery dependency we should avoid exposing its instances to the user, and that would be a breaking change anyways. 

## Alternatives

 - open to ideas about a better names for new finder methods
 - can we reduce number of args by putting `scope` to the `options`, so new interface gets:
```ts
// when no options passed
function findOne(pageObject: PageObjectNode, scope?: string): Element;
// scope is passed as a part of `options`
function findOne(pageObject: PageObjectNode, options?: FindOptions): Element;
```

**Comment by yratanov** [comment]
@ro0gr in which cases users will need to uses this function? I'm using ember-cli-page object in my project and haven't faced it yet. Though I used `executionContext.findWithAssert` method in my custom properties:

```js
export function powerSelect(selector) {
  return {
    isDescriptor: true,

    get() {
      return function(text) {
        const executionContext = getExecutionContext(this);
        return executionContext.runAsync(() => {
          const element = executionContext.findWithAssert(selector, {}).get(0);
          return selectChoose(element, text);
        });
      };
    }
  };
}
```

`findOne` might be confusing, since it's the same name as in new collection function, but with diffrent args.

**Comment by ro0gr** [comment]
> in which cases users will need to uses this function?

My use cases are the following:

```ts
export default {
  ...
  // inline getter
  opacity: getter(function(this: any) {
    const el = findElementWithAssert(this).get(0);
    return Number(getComputedStyle(el).opacity);
  }),

  // kind of action
  scrollToBottom() {
    const el = findElementWithAssert(this).get(0);
    el.scrollTop = el.scrollHeight;

    return this._triggerScroll();
  },

  _triggerScroll: triggerable('wheel')
}
``` 

or define custom props:

```ts
export default function hasFocus(scope?: string, options: object = {}) {
  return {
    isDescriptor: true,

    get(key: string) {
      const opts = Object.assign({ pageObjectKey: key }, options)

      const el = findElementWithAssert(this, scope, opts).get(0);

      return document.activeElement === el;
    }
  }
}
```

> Though I used `executionContext.findWithAssert`

`executionContext` private and for a good reason. There are many unnecessary internals exposed by this class. Using it in user land will complicate migration path for such apps. Currently, I'm working on extracting only the necessary bits from the current execution contexts to a new thing called adapters, hopefully I'll come up with an issue describing the plan for that this weekend. 

Talking specifically about `executionContext.findWithAssert`..  
In fact `findWithAssert` and `find` duplicate most of the logic between execution contexts. As far as I remember the only different thing for them is detecting a `contextElement`(second argument) of `$` query:

 - https://github.com/san650/ember-cli-page-object/blob/c37d364d7d0a6a075fa4f6b384011fe7a4946717/addon-test-support/-private/execution_context/rfc268.js#L109
 - https://github.com/san650/ember-cli-page-object/blob/c37d364d7d0a6a075fa4f6b384011fe7a4946717/addon-test-support/-private/execution_context/integration.js#L60
 - https://github.com/san650/ember-cli-page-object/blob/c37d364d7d0a6a075fa4f6b384011fe7a4946717/addon-test-support/-private/execution_context/acceptance.js#L120

In my opinion this should have been changed, so only `contextElement` is exposed from the execution context/adapter and the rest of the find logic is extracted to the finder method. 

---

> findOne might be confusing, since it's the same name as in new collection function, but with diffrent args.

yeah, I know what you mean. That's why I'm asking about ideas for better names in the alternatives sections.

By the way, it's not only about different args. They are used in different contexts. A new proposed `findOne`, `findMany` are standalone functions which has nothing to do with collections, and accept a page object instance as a first argument. I mean this naming collision is probably not such a bad thing, they are even used in different layer of the test suite:
 - `Collection.findOne` mostly used in tests itself
 - `findOne(pageObjectInstance, ...)` mostly in definitions

**Comment by yratanov** [comment]
@ro0gr got it. I use `executionContext` because `runAsync` is not exposed.

So this task will start 2.0 branch?

**Comment by ro0gr** [comment]
@yratanov I'd like to start v2 with only removal of deprecated apis.

The idea here is to:
 - Provide new finders
 - Switch to them internally in a backward compatible way, so consumers don't feel the difference. Seems like this should come with a minor version bump.
 - Suggest new finders in docs + deprecate `findElement(WithAssert)`. minor version bump again, this would probably be the last release of 1.x.

a bit out of scope here, but a similar strategy I'd like to apply for adapters, so when v2 starts we just remove all the legacy finders and all the execution contexts. 

does it make sense for you?

**Comment by yratanov** [comment]
@ro0gr in some cases you need to find element without assert. For example in `isHidden` property you want to count "element not found" as a valid result. Consumers would also like to have this ability in their custom properties. So I think asserting should be implicit. May be as a part of `options` hash, like `findOne(page, selector, { assert: true })`.

PS. It also made me think that we shouldn't have added asserts in #461, as there might also be reasonable use cases, like:
```js
assert.equal(collection.findOne('text', 'Lorem'), null, 'No Lorem in the list')
```

What do you think?

**Comment by ro0gr** [comment]
To check if element exist, it's meant to use `findMany`:

```js
const elementExists = findMany(this, scope, options).length === 1;
```

same with collections case, you can use `filter` there if you don't need stirct find.

**Comment by ro0gr** [comment]
Hey @karlbecker. Sure, here it is  https://github.com/ro0gr/ember-page-object-codemod/blob/HEAD/transforms/find-one/README.md

**Comment by karlbecker** [comment]
Thanks @ro0gr - and I apologize, I meant to reply on a different page talking about migrating from the `itemScope` change in an earlier version.

I got some help from an LLM though and it seems to have done a good job in making a codemod to convert from the legacy API collection `itemScope` approach: https://gist.github.com/karlbecker/50b98a1f511cbd02cd78bff430087c85

If you'd find that useful, feel free to add it to this repo - thanks!
