### ISSUE TITLE
Expose buildSelector for use in helpers

### ISSUE THREAD

**Issue by jrjohnson** [san650/ember-cli-page-object#470]
We have a helper that looks like:

```
export function fillInFroalaEditor(selector, options = {}) {
  return {
    isDescriptor: true,

    get() {
      return async function (html) {
        const elements = findElementWithAssert(this, selector, options);
        const editor = await getEditorInstance(elements[0]);
        editor.html.set(html);
      };
    }
  };
}
```

However this causes some issues and would work much better I could pass in a `selector` instead of an element, but I'm not sure how to get a correctly scoped selector from the helper. It appears that [buildSelector](https://github.com/san650/ember-cli-page-object/blob/master/addon-test-support/-private/helpers.js#L145) does that work, would it be possible to make this public so that the value returned from `findElementWithAssert` coule be able to be translated into a selector again?

Does this exist already and I just missed it?

**Comment by ro0gr** [comment]
Well, it's public https://github.com/san650/ember-cli-page-object/blob/master/addon-test-support/index.js#L26.

However, I believe we should avoid and deprecate it, cause `buildSelector`, in fact, is an internal implementation detail. 

Can you please provide more details? How JQuery selector produced by `buildSelector` is more useful for you than a native element? I'd like to know if we miss some usecase w/o `buildSelector`.

**Comment by jrjohnson** [comment]
Excellent, that's what I needed!

I don't think it's an internal detail here. I agree I shouldn't need it and it's probably a bug in the library I'm using that it can't take a DOMElement here. But all a helper gets is a partial selector `findElementWithAssert` can take that along with the context to return an element. Sometimes though you don't need DOMElement you need the full selector path so you can find it yourself.

In this specific case I would get `[data-test-html-editor]` as the `selector`, but `buildSelector` returns `[data-test-ilios-course-details] [data-test-detail-objectives] [data-test-html-editor]`. I can't think of another way from a helper to get all this context.
