### ISSUE TITLE
page object VS page object component

### ISSUE THREAD

**Issue by knownasilya** [san650/ember-cli-page-object#48]
What's the difference between the two? They look very similar, other then the fact that one uses `PO.build` and the other uses `PO.component`..

Would love documentation on components, helpers and pages. How they work together.

**Comment by juanazam** [comment]
The main difference is that using `build` always assume that you are setting the scope of the component to be created based on its definition while in the `component` function if there is not `scope` in the definition inherits the scope from its parent, thats why `component` should be use inside a page definition using `build`.

build: https://github.com/san650/ember-cli-page-object/blob/master/test-support/page-object/build.js#L56
component: https://github.com/san650/ember-cli-page-object/blob/master/test-support/page-object/build.js#L41

Hope I was clear enough :smile: 

Regarding documentation about helpers, I believe the [documentation](https://github.com/san650/ember-cli-page-object/blob/master/DOCUMENTATION.md#component) is pretty complete, but if you have any particular doubts we are willing to help.

**Comment by knownasilya** [comment]
Makes sense.

Regarding the documentation, I wasn't aware that even existed (or forgot), since I didn't see a link to it in the readme.

**Comment by san650** [comment]
@knownasilya The main difference about pages and components is that components are reusable among several pages, pages on the other hand cannot be used like attributes on other pages... or are not supposed to (the scope is transferred to components).

The README has a link to the documentation below the first examples (above BLUEPRINTS title), we'll change the README to make it more prominently.

We're planning on building a website for the addon to make the documentation more accesible, please let us know if you find the documentation useful or if you think we need to improve it.

Thank you!

**Comment by san650** [comment]
Hi @knownasilya, please let me know if I can close this issue or if you have more questions regarding this.


Thanks!

**Comment by knownasilya** [comment]
Thanks :)
