### ISSUE TITLE
Can I use ember-cli-page-objects with ember-cli-mocha

### ISSUE THREAD

**Issue by kiwiupover** [san650/ember-cli-page-object#52]
Cheers

**Comment by san650** [comment]
Hi @kiwiupover, although I didn't try to use ember-cli-page-object with ember-cli-mocha, I don't see why it wouldn't be compatible. I'll create a small demo app with this and let you know how it goes.

**Comment by san650** [comment]
I've just created a small application to test this and it works great!

Please, let me know if you find any issue or have any other concern.
