### ISSUE TITLE
Update ember-cli-babel

### ISSUE THREAD

**Issue by cah-briangantzler** [san650/ember-cli-page-object#573]
Ember-cli-babel needs to be updated to at least 7.26.1. The below is happening and preventing an upgrade to Ember 4

Prior to v7.26.6, ember-cli-babel sometimes transpiled imports into the equivalent Ember Global API, potentially triggering this deprecation message indirectly, even when you did not observe these deprecated usages in your code.

**Comment by ro0gr** [comment]
fixed in https://github.com/san650/ember-cli-page-object/pull/574. Thanks!

**Comment by rtablada** [comment]
@ro0gr since this was merged can a 1.17.10 get published?

**Comment by ro0gr** [comment]
@rtablada sure, will do it today

**Comment by ro0gr** [comment]
https://github.com/san650/ember-cli-page-object/releases/tag/v1.17.10

**Comment by ro0gr** [comment]
For the record, I suspect even with this change it still won't be possible upgrade to Ember 4 against ember-cli-page-object@1 due to "@ember/polyfills" usage https://github.com/san650/ember-cli-page-object/issues/571
