### ISSUE TITLE
migrate to v2 Addon Format

### ISSUE THREAD

**Issue by ro0gr** [san650/ember-cli-page-object#575]

**Comment by ro0gr** [comment]
Probably the first question would be to decide on the test-app strategy. 

Sometimes ago I have tried an in-package test-app, but I had somewhat poor dev experience managing the dependencies consistency, though maybe it was because of my curly hands.

At the moment I tend to choose a monorepo approach(though not experienced with monorepos), cause I believe it should be clearer depependencies management, and also there are some sings to me that we should finally extract the core from the ember-cli-page-object part at some point, and they both could conveniently live under the same monorepo umbrella.

@SergeAstapov may you share your preference this topic based on your experience please?

**Comment by SergeAstapov** [comment]
@ro0gr it’s indeed much simpler to go monorepo setup and manage test app as separate package within the monorepo.
As a bonus, you can setup separate docs app in the same monorepo or even have multiple test apps should they have some different setup

**Comment by SergeAstapov** [comment]
And as you said, managing dependencies for the test app separately from the addon is so much simpler than otherwise!

**Comment by SergeAstapov** [comment]
@ro0gr just did PR https://github.com/san650/ember-cli-page-object/pull/576
it's huge one, so we can chat/discuss or even jump a call if that would work for you to expedite the review and convo.
