### ISSUE TITLE
Types require allowSyntheticDefaultImports=true

### ISSUE THREAD

**Issue by HeroicEric** [san650/ember-cli-page-object#589]
Related to https://github.com/san650/ember-cli-page-object/pull/582

The current type definitions require that an app have the [`allowSyntheticDefaultImports` option](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports) set to `"true"` in their `.tsconfig` to avoid the following error:

```
node_modules/ember-cli-page-object/types/index.d.ts:61:10 - error TS1259: Module '"/MYAPP/node_modules/@types/jquery/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

61   import JQuery from 'jquery';
```

[`@tsconfig/ember` sets `allowSyntheticDefaultImports` to `false` by default with some reasoning in the comments](https://github.com/tsconfig/bases/blob/main/bases/ember.json#L28-L38).

Usually this can be fixed by changing the imports to the following but I have not actually tried to do so yet:

```
import * as JQuery from 'jquery';
```

**Comment by ro0gr** [comment]
Thanks for reporting! Yeah, getting rid of synthetic imports sounds like a good idea. I've started playing with this here https://github.com/san650/ember-cli-page-object/pull/590, but it still needs some time to push it across the finish line.

**Comment by ro0gr** [comment]
Just released the fix as a part of https://github.com/san650/ember-cli-page-object/releases/tag/v1.17.12
