### ISSUE TITLE
Replace usage of ember-native-dom-helpers by @ember/test-helpers

### ISSUE THREAD

**Issue by Frank3K** [san650/ember-cli-page-object#592]
ember-cli-page-object v1.17.11 relies on [ember-native-dom-helpers](https://github.com/cibernox/ember-native-dom-helpers). The ember-native-dom-helpers package is end-of-life and relies on ember-cli-babel@6, which is a problem for upgrading to Ember 4.

A solution would be to replace the use of ember-native-dom-helpers by [@ember/test-helpers](https://github.com/emberjs/ember-test-helpers), as it is the suggested way forward from ember-native-dom-helpers: https://github.com/cibernox/ember-native-dom-helpers/issues/147.

**Comment by ro0gr** [comment]
Hey @Frank3K 👋  

It's unlikely, that ember-native-dom-helpers will be removed in scope of v1. I'd suggest to give a try to the [v2.0.0-beta.4](https://github.com/san650/ember-cli-page-object/releases/tag/v2.0.0-beta.4) which doesn't have ember-native-dom-helpers as a dependency anymore.
