### ISSUE TITLE
docs: clickable needs to be awaited

### ISSUE THREAD

**Issue by nicolechung** [san650/ember-cli-page-object#603]
I think clickable needs to be awaited [because it runs asynchronously](https://github.com/san650/ember-cli-page-object/blob/master/addon-test-support/properties/clickable.js#L77)

This is confusing because in the overview it's `awaited`: http://ember-cli-page-object.js.org/docs/v1.17.x/

But in the docs for clickable it's not: http://ember-cli-page-object.js.org/docs/v1.17.x/api/clickable

**Comment by ro0gr** [comment]
I agree. I think this is a left over from the moduleFor fashion tests. As far as I can see the same issue is applicable to the rest of actions:
 - http://ember-cli-page-object.js.org/docs/v1.17.x/api/blurrable
 - http://ember-cli-page-object.js.org/docs/v1.17.x/api/click-on-text
 - http://ember-cli-page-object.js.org/docs/v1.17.x/api/fillable
 - http://ember-cli-page-object.js.org/docs/v1.17.x/api/focusable
 - http://ember-cli-page-object.js.org/docs/v1.17.x/api/triggerable
 - http://ember-cli-page-object.js.org/docs/v1.17.x/api/visitable

I believe we can safely prepend all such invocations with `await`. PR is welcome!

**Comment by ro0gr** [comment]
just in case, documentation is placed along the source code. Clickable for an example https://github.com/san650/ember-cli-page-object/blob/77b13a33e59fb1a7cfd01a9bad41ee34f7d1dddf/addon-test-support/properties/clickable.js#L7-L67
