### ISSUE TITLE
string getters on a collection definition raise error

### ISSUE THREAD

**Issue by simonihmig** [san650/ember-cli-page-object#637]
We have a large number of string props (selector strings) on page objects. While there are certainly better ways to use POs and write tests, _without_ those string props, doing the upgrade to v2 _and_ removing that tech debt at the same time is impossible, due to the scale of our code base. 

So for now I am applying the escape hatch described in the [deprecation guide](https://ember-cli-page-object.js.org/docs/v1.17.x/deprecations#string-properties-on-definition) and turning those into getters (codemod). So far so good. But in one case this approach fails, where you have a definition with a getter as part of a `collection()`. When accessing a single item of that collection via `objectAt`, that definition is cloned [here](https://github.com/san650/ember-cli-page-object/blob/28b1d8b29cf038927b5340e0c3f54b66ef358933/addon/src/properties/collection.js#L202), which "flattens" all getters into simple props. Later on, this simple string prop is then throwing that `string values are not supported in page object definitions` error.

As there is explicit support for getters, I think we should be able to make a clone of a definition that retains all own getters ([example](https://stackoverflow.com/a/34481052))!? @ro0gr does that make sense?

**Comment by ro0gr** [comment]
Hey, thanks for the report! I believe we do a similar thing but in the `create` https://github.com/san650/ember-cli-page-object/blob/28b1d8b29cf038927b5340e0c3f54b66ef358933/addon/src/create.js#L10-L18. It seems reasonable to reuse it for Collections as well.

**Comment by simonihmig** [comment]
Ah, thanks for pointing that out! I can work on a PR tomorrow then! 🙂
