### ISSUE TITLE
Unknown blueprint: page-object | page-object-component

### ISSUE THREAD

**Issue by michaelchadwick** [san650/ember-cli-page-object#641]
Installed latest 2.30 version in an Ember 5.9 application, and tried running `ember generate page-object about-page`. I get the error: `Unknown blueprint: page-object`. Same type of issue with `ember generate page-object-component contact-form`.

**Comment by ro0gr** [comment]
Hey, it should be fixed in the https://github.com/san650/ember-cli-page-object/releases/tag/v2.3.1 now. Thanks everyone!
