### ISSUE TITLE
Define attributes without a selector if the page has an scope defined

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#7]
Sometimes is handy to create a page or component and be able to define child attributes without setting a selector. For example:

```html
<div class="modal">
  <!-- modal content -->
</div>
```

```js
let page = PageObject.build({
  modal: component({
    scope: '.modal',

    isVisible: isVisible(),
    isHidden: isHidden(),
    isError: hasClass('error')
  })
});
```

In this case, the attributes `isVisible`, `isHidden` and `isError` validate properties on the `.modal` element. 

__Right now this works but is not officially supported, so we need to create tests and documentations for this behavior.__

As an added bonus, this definition can be improved using the new ES6 object literal shorthand assignments:

```js
let page = PageObject.build({
  modal: component({
    scope: '.modal',

    isVisible,
    isHidden,
    isError: hasClass('error')
  })
});
```

**Comment by knownasilya** [comment]
Nice, what is `component(..)` in this context?

**Comment by juanazam** [comment]
@knownasilya it refers to: https://github.com/san650/ember-cli-page-object/blob/master/DOCUMENTATION.md#component :)

**Comment by knownasilya** [comment]
Nice, that's new since previously it was just a POJO, right?

**Comment by juanazam** [comment]
Actually es the other way round, on the first versions of the addon, you had to specify components explicitly. In the latest versions, if you use a POJO, the addon will automatically convert it into a PagehObject object (so the PageObject definition is less bulky).

**Comment by knownasilya** [comment]
Good to know. Thanks.
