### ISSUE TITLE
An action for datetimepicker

### ISSUE THREAD

**Issue by NeilAllen** [san650/ember-cli-page-object#90]
There can't be many site out there without datetimepickers; can't get fillable action to work with datetimepicker. Is this a short-coming or am I doing it wrong?

var page = PageObject.create({
  name: PageObject.fillable('.input-start-date')
});

**Comment by juanazam** [comment]
Hey @NeilAllen, can you provide more information? which date time picker are you using? is it rendering correctly on the tests environment?

**Comment by NeilAllen** [comment]
Hi!, thanks for the reply.

We are using the ember-bootstrap-datetimepicker (https://github.com/plusacht/ember-bootstrap-datetimepicker.git)

We have developed a workaround, to be honest, which does what I was asking about.

Thanks for your time.

N

**Comment by san650** [comment]
@NeilAllen can you share the workaround? So, we understand what the problem was and It might help other users also.

Thanks and sorry we weren't able to help you with the issue
