### ISSUE TITLE
Feature: Page objects in integration tests for components

### ISSUE THREAD

**Issue by jeradg** [san650/ember-cli-page-object#96]
This addon is great in acceptance tests, so I thought I would try using page objects to DRY up my integration tests for Ember components. This seemed like it might be straightforward, since pages are structured based on components anyway, and almost all of the page-object methods would be useful in component tests (except `visitable()`).

This doesn't currently work, however, because ember-cli-page-object uses the global `find()` to query selectors, which is only available in acceptance tests. (There may be other issues as well, but this one blocked me from looking any further.)

To fix this in integration tests, I suspect that the page object would just need access to `this.$()` instead of `find()`. I'm happy to try this out and (hopefully) submit a PR with page objects that can be configured to work in integration tests.

Just wanted to be sure that this isn't already a feature-in-progress, or that this use case hasn't been ruled out for some reason.

**Comment by jeradg** [comment]
Just took another look at the codebase and noticed that there are a number of global acceptance test helpers in use. (`click()`, etc.) These would have to be replaced with their integration counterparts as well, but that should be equally doable.

**Comment by csantero** [comment]
@jeradg See the discussion in #79. At the moment the workaround is to start the app for each component integration test.

**Comment by jeradg** [comment]
OK, thanks. I'll restrict page objects to my acceptance tests for now.
