### ISSUE TITLE
[Feature] Support for component integration tests

### ISSUE THREAD

**Issue by jeradg** [san650/ember-cli-page-object#97]
(*Discussion continued from #79.*)

Page objects would be useful in component integration tests. To make this possible, a page object would need access to the test's `this` context, in order to access `this.$()`, `this.render()`, etc.

**Comment by jeradg** [comment]
@san650 @csantero Some thoughts on passing the test's context to `Page.create()` (or `extend()`, for that matter):

I don't think that passing the context as its own argument would work well (`Page.create(this)`). First, users still need to be able to pass an object to `create()`, i.e.:

```js
let page = Page.create({something: clickable('#a-thing')});
```

So if we passed `this` as a separate argument, it would look like

```js
let page = Page.create({something: clickable('#a-thing')}, this);

/* or... */

let page = Page.create({}, this);

/* or... */

let page = Page.create(this, {something: clickable('#a-thing')});
```

This sounds like a pain to me, because we would have to check to see if the first argument passed to `create()` is a context. (How would that even work?)

Second, I'm not sure how we would write tests with this approach to make sure that the test's `this` is being received by the page object.

My suggestion:

```js
let page = Page.create({
  context: this
});
```

So if `!!page.context === true`, then `page.context` will be used as the context for `find()`, action helpers, etc.

In ember-cli-page-object's internal tests, we can do something like:

```js
let page = Page.create({context: this});

assert.equal(this, page.context);
assert.equal(this.$, page.context.$);

/* etc... */
```

Thoughts?

**Comment by csantero** [comment]
:+1: for

```
let page = Page.create({
  context: this
});
```

**Comment by jeradg** [comment]
I've started work at https://github.com/jeradg/ember-cli-page-object/tree/component-integration-test-support.

@san650 I forked off of master. Let me know if there's a particular branch I should be merging from to keep up-to-date on your `extend()`/`create()` changes. I hesitate to do too much work on actually implementing the feature (vs. writing tests) until you're further along with those 1.0 changes. (Also, I haven't started a PR yet since there isn't a "one-point-one" branch to target.)

**Comment by jeradg** [comment]
Failing tests have been added for component integration test support.

https://github.com/san650/ember-cli-page-object/compare/master...jeradg:component-integration-test-support

I based the integration tests off of the existing acceptance tests, so this should be a good starting point.

Comments are welcome on the suggested syntax. (It's nothing fancy.)

**Comment by donovan-graham** [comment]
:+1: I support this request.

I'm looking into this exact same use case and would like to see it materialize.  

I ran into problems with the default Ember test helpers that are registered for acceptance tests. e.g click, find, findWithAssert.  These all seem to rely on an Ember app being initialized and backed by the `wait` 

https://github.com/emberjs/ember.js/blob/f4b1e6622d197c188993dda06fdb10310189f633/packages/ember-testing/lib/helpers.js#L80

**Comment by donovan-graham** [comment]
:+1: for this implementation


// tests/pages/components/my-component.js
```
const { clickable } = PageObject;
let myComponentDSL = {submit: clickable('button#button')};
```

// test/integration/component/my-component.js
```
import PageObject from '../../page-object';
let componentPO = Page.create(myComponentDSL, { context: this});
componentPO.submit();
```

This would also allow the component definition to be composable part of an acceptance test page DSL.

**Comment by jeradg** [comment]
@donovan-graham In the context of an integration test, my instinct is that the helpers would be synchronous and would use the jQuery helpers. No need to an app instance or `wait`.

Do you have an example use-case for async page-object helpers in component tests? We could probably figure out a way to tie promises into the implementation, but my thought is that it would be overkill. Users could still use promises to make the tests async when necessary.

**Comment by donovan-graham** [comment]
@jeradg Agreed. If a particular use case comes to mind I'll post it.

**Comment by jeradg** [comment]
@donovan-graham @csantero: As of ember-cli-page-object v1.1.0, you can now use page objects in component integration tests!

See the [v1.1.0 release notes](https://github.com/san650/ember-cli-page-object/releases/tag/v1.1.0) and the new [quickstart guide](http://ember-cli-page-object.js.org/docs/v1.1.x/quickstart) to get started.

*Closed by https://github.com/san650/ember-cli-page-object/pull/99*
